Backend: fix possible exception when renaming DAI to SAI accounts
Not entirely sure how this might have happened except for when trying
the new multi-collateral DAI currency branch which is WIP (but yes
this happened in my cold storage testing machine).

Exception was:
System.IO.IOException: The file '/Users/knocte/.config/gwallet/accounts/SAI/UTC--2019-06-24T10-41-53.6974610Z--87f494bB0eF7C06E37a8024a555e21C06D679e55' already exists.
  at System.IO.FileSystem.LinkOrCopyFile (System.String sourceFullPath, System.String destFullPath) [0x000b1] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-10/external/bockbuild/builds/mono-x64/external/corefx/src/System.IO.FileSystem/src/System/IO/FileSystem.Unix.cs:117
  at System.IO.FileSystem.MoveFile (System.String sourceFullPath, System.String destFullPath) [0x0003a] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-10/external/bockbuild/builds/mono-x64/external/corefx/src/System.IO.FileSystem/src/System/IO/FileSystem.Unix.cs:181
  at System.IO.File.Move (System.String sourceFileName, System.String destFileName) [0x00083] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-10/external/bockbuild/builds/mono-x64/external/corefx/src/System.IO.FileSystem/src/System/IO/File.cs:644
  at GWallet.Backend.Config.RenameDaiAccountsToSai () [0x0006b] in /Users/knocte/Documents/Code/geewalletSTABLE/src/GWallet.Backend/Config.fs:128
  at GWallet.Backend.Account.GetAllActiveAccounts () [0x00000] in /Users/knocte/Documents/Code/geewalletSTABLE/src/GWallet.Backend/Account.fs:49
  at Program.ProgramMainLoop[a] () [0x00000] in /Users/knocte/Documents/Code/geewalletSTABLE/src/GWallet.Frontend.Console/Program.fs:353
  at Program.NormalStartWithNoParameters () [0x00007] in /Users/knocte/Documents/Code/geewalletSTABLE/src/GWallet.Frontend.Console/Program.fs:366
System.IO.IOException: The file '/Users/knocte/.config/gwallet/accounts/SAI/UTC--2019-06-24T10-41-53.6974610Z--87f494bB0eF7C06E37a8024a555e21C06D679e55' already exists.
  at GWallet.Backend.Infrastructure.Report[a] (System.Exception ex, SharpRaven.Data.ErrorLevel errorLevel) [0x0000b] in /Users/knocte/Documents/Code/geewalletSTABLE/src/GWallet.Backend/Infrastructure.fs:33
  at GWallet.Backend.Infrastructure.ReportCrash[a] (System.Exception ex) [0x00000] in /Users/knocte/Documents/Code/geewalletSTABLE/src/GWallet.Backend/Infrastructure.fs:46
  at Program.NormalStartWithNoParameters () [0x00017] in /Users/knocte/Documents/Code/geewalletSTABLE/src/GWallet.Frontend.Console/Program.fs:370
  at Program.main (System.String[] argv) [0x0002b] in /Users/knocte/Documents/Code/geewalletSTABLE/src/GWallet.Frontend.Console/Program.fs:388
exception inside UnhandledException handler: (null) assembly:/Library/Frameworks/Mono.framework/Versions/6.8.0/lib/mono/4.5/mscorlib.dll type:IOException member:(null)