Backend/Ether: add 2 more ETH nodes (leave one commented)
They come from these eth-prefixed files:
https://github.com/MyEtherWallet/MyEtherWallet/tree/master/src/networks/nodes

However it seems the EtherScan one doesn't work because it throws
this exception (TODO: file bug in Nethereum/JsonRpcSharp):

System.Exception: Call to access the DAI balance somehow returned unexpected error ---> System.AggregateException: One or more errors occurred. ---> System.Exception: Some problem when connecting to https://api.etherscan.io/api ---> System.AggregateException: One or more errors occurred. ---> Nethereum.JsonRpc.Client.RpcClientUnknownException: Error occurred when trying to send rpc requests(s) ---> Newtonsoft.Json.JsonSerializationException: Required property 'id' not found in JSON. Path '', line 1, position 81.
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EndProcessProperty (System.Object newObject, Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonObjectContract contract, System.Int32 initialDepth, Newtonsoft.Json.Serialization.JsonProperty property, Newtonsoft.Json.Serialization.JsonSerializerInternalReader+PropertyPresence presence, System.Boolean setDefaultValue) [0x00181] in <dc86da7fc46c487ba6c7ab826da479cc>:0
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject (System.Object newObject, Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonObjectContract contract, Newtonsoft.Json.Serialization.JsonProperty member, System.String id) [0x002d3] in <dc86da7fc46c487ba6c7ab826da479cc>:0
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) [0x00161] in <dc86da7fc46c487ba6c7ab826da479cc>:0
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) [0x0006d] in <dc86da7fc46c487ba6c7ab826da479cc>:0
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) [0x000db] in <dc86da7fc46c487ba6c7ab826da479cc>:0
  at Newtonsoft.Json.JsonSerializer.DeserializeInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00053] in <dc86da7fc46c487ba6c7ab826da479cc>:0
  at Newtonsoft.Json.JsonSerializer.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00000] in <dc86da7fc46c487ba6c7ab826da479cc>:0
  at Newtonsoft.Json.JsonSerializer.Deserialize[T] (Newtonsoft.Json.JsonReader reader) [0x00000] in <dc86da7fc46c487ba6c7ab826da479cc>:0
  at Nethereum.JsonRpc.Client.RpcClient+<SendAsync>d__17.MoveNext () [0x001f5] in <637b104e55b941dcb1efbb91e63ee797>:0
   --- End of inner exception stack trace ---
  at Nethereum.JsonRpc.Client.RpcClient+<SendAsync>d__17.MoveNext () [0x00286] in <637b104e55b941dcb1efbb91e63ee797>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <71f4e3d7d65e42b0a699d02e59766d3c>:0
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <71f4e3d7d65e42b0a699d02e59766d3c>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <71f4e3d7d65e42b0a699d02e59766d3c>:0
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <71f4e3d7d65e42b0a699d02e59766d3c>:0
  at Nethereum.JsonRpc.Client.RpcClient+<SendInnerRequestAync>d__12`1[T].MoveNext () [0x000a2] in <637b104e55b941dcb1efbb91e63ee797>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <71f4e3d7d65e42b0a699d02e59766d3c>:0
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <71f4e3d7d65e42b0a699d02e59766d3c>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <71f4e3d7d65e42b0a699d02e59766d3c>:0
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <71f4e3d7d65e42b0a699d02e59766d3c>:0
  at Nethereum.JsonRpc.Client.ClientBase+<SendRequestAsync>d__4`1[T].MoveNext () [0x0014f] in <5b4585c1c99947d78244d74142f50fce>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <71f4e3d7d65e42b0a699d02e59766d3c>:0
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <71f4e3d7d65e42b0a699d02e59766d3c>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <71f4e3d7d65e42b0a699d02e59766d3c>:0
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <71f4e3d7d65e42b0a699d02e59766d3c>:0
  at Nethereum.Contracts.FunctionBase+<CallAsync>d__17`1[TReturn].MoveNext () [0x0008d] in <35be2653c4244880a0877b501e5752c0>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <71f4e3d7d65e42b0a699d02e59766d3c>:0
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <71f4e3d7d65e42b0a699d02e59766d3c>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <71f4e3d7d65e42b0a699d02e59766d3c>:0
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <71f4e3d7d65e42b0a699d02e59766d3c>:0
  at Nethereum.StandardTokenEIP20.StandardTokenService+<GetBalanceOfAsync>d__16`1[T].MoveNext () [0x00089] in <4578db8b19274bc3897d34b77597bceb>:0
   --- End of inner exception stack trace ---
  at System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) [0x00011] in <71f4e3d7d65e42b0a699d02e59766d3c>:0
  at System.Threading.Tasks.Task.Wait (System.Int32 millisecondsTimeout, System.Threading.CancellationToken cancellationToken) [0x00043] in <71f4e3d7d65e42b0a699d02e59766d3c>:0
  at System.Threading.Tasks.Task.Wait (System.TimeSpan timeout) [0x00022] in <71f4e3d7d65e42b0a699d02e59766d3c>:0
  at GWallet.Backend.Ether.Server.WaitOnTask[T,R] (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] func, T arg) [0x00059] in <5bbac1f65952d4f0a7450383f6c1ba5b>:0
  at GWallet.Backend.Ether.Server+web3Func@232-4.Invoke (Nethereum.Web3.Web3 web3, System.String publicAddress) [0x0000f] in <5bbac1f65952d4f0a7450383f6c1ba5b>:0
  at Microsoft.FSharp.Core.OptimizedClosures+Invoke@3253[T2,TResult,T1].Invoke (T2 u) [0x00001] in <59964427904cf4daa745038327449659>:0
  at GWallet.Backend.Ether.Server+GetUnconfirmedTokenBalance@236-2.Invoke (System.String arg10) [0x00000] in <5bbac1f65952d4f0a7450383f6c1ba5b>:0
  at Microsoft.FSharp.Core.FSharpFunc`2[T,TResult].InvokeFast[V] (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] func, T arg1, TResult arg2) [0x0001f] in <59964427904cf4daa745038327449659>:0
  at GWallet.Backend.Ether.Server+serverFuncs@194[T,R].Invoke (GWallet.Backend.Ether.Server+SomeWeb3 web3, T arg) [0x00000] in <5bbac1f65952d4f0a7450383f6c1ba5b>:0
   --- End of inner exception stack trace ---
  at <StartupCode$GWallet-Backend>.$FaultTolerantParallelClient+clo@108-12[E,T,R].Invoke (System.Exception _arg2) [0x000c6] in <5bbac1f65952d4f0a7450383f6c1ba5b>:0
  at Microsoft.FSharp.Control.AsyncBuilderImpl+tryWithExnA@881[a].Invoke (System.Runtime.ExceptionServices.ExceptionDispatchInfo edi) [0x0000d] in <59964427904cf4daa745038327449659>:0
  at Microsoft.FSharp.Control.AsyncBuilderImpl+callA@839[b,a].Invoke (Microsoft.FSharp.Control.AsyncParams`1[T] args) [0x00052] in <59964427904cf4daa745038327449659>:0
   --- End of inner exception stack trace ---
  at System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) [0x00011] in <71f4e3d7d65e42b0a699d02e59766d3c>:0
  at System.Threading.Tasks.Task`1[TResult].GetResultCore (System.Boolean waitCompletionNotification) [0x0002b] in <71f4e3d7d65e42b0a699d02e59766d3c>:0
  at System.Threading.Tasks.Task`1[TResult].get_Result () [0x0000f] in <71f4e3d7d65e42b0a699d02e59766d3c>:0
  at <StartupCode$GWallet-Backend>.$FaultTolerantParallelClient+clo@62-8[E,T,R].Invoke (System.Threading.Tasks.Task`1[TResult] _arg1) [0x00002] in <5bbac1f65952d4f0a7450383f6c1ba5b>:0
  at Microsoft.FSharp.Control.AsyncBuilderImpl+args@823-1[a,b].Invoke (a a) [0x00016] in <59964427904cf4daa745038327449659>:0
   --- End of inner exception stack trace ---
  at GWallet.Backend.Account+GetBalanceFromServerOrCache@29-4.Invoke (System.Exception _arg2) [0x00056] in <5bbac1f65952d4f0a7450383f6c1ba5b>:0
  at Microsoft.FSharp.Control.AsyncBuilderImpl+tryWithExnA@881[a].Invoke (System.Runtime.ExceptionServices.ExceptionDispatchInfo edi) [0x0000d] in <59964427904cf4daa745038327449659>:0
  at Microsoft.FSharp.Control.AsyncBuilderImpl+callA@839[b,a].Invoke (Microsoft.FSharp.Control.AsyncParams`1[T] args) [0x00052] in <59964427904cf4daa745038327449659>:0
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a] (Microsoft.FSharp.Control.AsyncBuilderImpl+AsyncImplResult`1[T] res) [0x0002d] in <59964427904cf4daa745038327449659>:0
  at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronouslyInCurrentThread[a] (System.Threading.CancellationToken token, Microsoft.FSharp.Control.FSharpAsync`1[T] computation) [0x00029] in <59964427904cf4daa745038327449659>:0
  at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a] (System.Threading.CancellationToken token, Microsoft.FSharp.Control.FSharpAsync`1[T] computation, Microsoft.FSharp.Core.FSharpOption`1[T] timeout) [0x00014] in <59964427904cf4daa745038327449659>:0
  at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T] (Microsoft.FSharp.Control.FSharpAsync`1[T] computation, Microsoft.FSharp.Core.FSharpOption`1[T] timeout, Microsoft.FSharp.Core.FSharpOption`1[T] cancellationToken) [0x00071] in <59964427904cf4daa745038327449659>:0
  at GWallet.Frontend.Console.UserInteraction.DisplayAccountStatuses (GWallet.Frontend.Console.WhichAccount whichAccount) [0x00056] in <5bbac1fa48ab50f3a7450383fac1ba5b>:0
  at Program.ProgramMainLoop[a] () [0x0000c] in <5bbac1fa48ab50f3a7450383fac1ba5b>:0
  at Program.main (System.String[] argv) [0x00007] in <5bbac1fa48ab50f3a7450383fac1ba5b>:0