Fix .NETStandard-related compilation errors
They were:
FSharpUtil.fs(3,12): error FS1108: The type 'IEquatable`1' is required here and is unavailable. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
FSharpUtil.fs(8,37): error FS0039: The type 'Exception' is not defined