scripts/make.fsx: adjust MONO_PATH for (gtk)snap
We were getting exception for all gtk-sharp related libs, such as:

[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'gtk-sharp, Version=2.12.0.0, Culture=neutral, PublicKeyToken=35e10195dab3c99f' or one of its dependencies.
File name: 'gtk-sharp, Version=2.12.0.0, Culture=neutral, PublicKeyToken=35e10195dab3c99f'

[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'glib-sharp, Version=2.12.0.0, Culture=neutral, PublicKeyToken=35e10195dab3c99f' or one of its dependencies.
File name: 'glib-sharp, Version=2.12.0.0, Culture=neutral, PublicKeyToken=35e10195dab3c99f'

[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'atk-sharp, Version=2.12.0.0, Culture=neutral, PublicKeyToken=35e10195dab3c99f' or one of its dependencies.
File name: 'atk-sharp, Version=2.12.0.0, Culture=neutral, PublicKeyToken=35e10195dab3c99f'

[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type of field 'Xamarin.Forms.Platform.GTK.FormsWindow:_lastSize' (1) due to: Could not load file or assembly 'gdk-sharp, Version=2.12.0.0, Culture=neutral, PublicKeyToken=35e10195dab3c99f' or one of its dependencies.

Exception in Gtk# callback delegate
  Note: Applications can use GLib.ExceptionManager.UnhandledException to handle the exception.
System.IO.FileNotFoundException: Could not load file or assembly 'pango-sharp, Version=2.12.0.0, Culture=neutral, PublicKeyToken=35e10195dab3c99f' or one of its dependencies.
File name: 'pango-sharp, Version=2.12.0.0, Culture=neutral, PublicKeyToken=35e10195dab3c99f'
  at Xamarin.Forms.Platform.GTK.Extensions.LabelExtensions.SetTextFromSpan (Gtk.Label self, Xamarin.Forms.Span span) [0x00000] in <fd79b85f7e1e4bec84e0202e121dbd99>:0
  at Xamarin.Forms.Platform.GTK.Renderers.LabelRenderer.UpdateText () [0x00087] in <fd79b85f7e1e4bec84e0202e121dbd99>:0
  at Xamarin.Forms.Platform.GTK.Renderers.LabelRenderer.OnElementChanged (Xamarin.Forms.Platform.GTK.ElementChangedEventArgs`1[TElement] e) [0x0001b] in <fd79b85f7e1e4bec84e0202e121dbd99>:0
  at Xamarin.Forms.Platform.GTK.VisualElementRenderer`2[TElement,TNativeElement].SetElement (TElement element) [0x0008b] in <fd79b85f7e1e4bec84e0202e121dbd99>:0
  at Xamarin.Forms.Platform.GTK.VisualElementRenderer`2[TElement,TNativeElement].Xamarin.Forms.Platform.GTK.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00000] in <fd79b85f7e1e4bec84e0202e121dbd99>:0
  at Xamarin.Forms.Platform.GTK.Platform.CreateRenderer (Xamarin.Forms.VisualElement element) [0x00014] in <fd79b85f7e1e4bec84e0202e121dbd99>:0
  at Xamarin.Forms.Platform.GTK.Packagers.LayoutElementPackager.OnChildAdded (Xamarin.Forms.VisualElement view) [0x00000] in <fd79b85f7e1e4bec84e0202e121dbd99>:0
  at Xamarin.Forms.Platform.GTK.Packagers.VisualElementPackager`1[TElementRenderer].Load () [0x0001e] in <fd79b85f7e1e4bec84e0202e121dbd99>:0
  at Xamarin.Forms.Platform.GTK.Renderers.LayoutRenderer.OnElementChanged (Xamarin.Forms.Platform.GTK.ElementChangedEventArgs`1[TElement] e) [0x00079] in <fd79b85f7e1e4bec84e0202e121dbd99>:0
  at Xamarin.Forms.Platform.GTK.VisualElementRenderer`2[TElement,TNativeElement].SetElement (TElement element) [0x0008b] in <fd79b85f7e1e4bec84e0202e121dbd99>:0
  at Xamarin.Forms.Platform.GTK.VisualElementRenderer`2[TElement,TNativeElement].Xamarin.Forms.Platform.GTK.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00000] in <fd79b85f7e1e4bec84e0202e121dbd99>:0
  at Xamarin.Forms.Platform.GTK.Platform.CreateRenderer (Xamarin.Forms.VisualElement element) [0x00014] in <fd79b85f7e1e4bec84e0202e121dbd99>:0
  at Xamarin.Forms.Platform.GTK.Packagers.PageElementPackager.OnChildAdded (Xamarin.Forms.VisualElement view) [0x00000] in <fd79b85f7e1e4bec84e0202e121dbd99>:0
  at Xamarin.Forms.Platform.GTK.Packagers.VisualElementPackager`1[TElementRenderer].Load () [0x0001e] in <fd79b85f7e1e4bec84e0202e121dbd99>:0
  at Xamarin.Forms.Platform.GTK.Renderers.PageRenderer.OnShown () [0x0001a] in <fd79b85f7e1e4bec84e0202e121dbd99>:0
  at Gtk.Widget.shown_cb (System.IntPtr widget) [0x0000d] in <7aab76e87bce48a4b45cf7fa613cb70c>:0
  at GLib.ExceptionManager.RaiseUnhandledException (System.Exception e, System.Boolean is_terminal) [0x00000] in <ed39f21b9e9343dcbd442a17ad356a9f>:0
  at Gtk.Widget.shown_cb (System.IntPtr widget) [0x00000] in <7aab76e87bce48a4b45cf7fa613cb70c>:0
  at Gtk.Widget.gtk_widget_show_all (System.IntPtr ) [0x00000] in <7aab76e87bce48a4b45cf7fa613cb70c>:0
  at Gtk.Widget.ShowAll () [0x00000] in <7aab76e87bce48a4b45cf7fa613cb70c>:0
  at Xamarin.Forms.Platform.GTK.Renderers.NavigationPageRenderer.AddPageAsync (Xamarin.Forms.Page page, System.Boolean animated) [0x00000] in <fd79b85f7e1e4bec84e0202e121dbd99>:0
  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[TResult].Start[TStateMachine] (TStateMachine& stateMachine) [0x00000] in <d2ec5c92492f4d6ba8c422bdf574b786>:0
  at Xamarin.Forms.Platform.GTK.Renderers.NavigationPageRenderer.AddPageAsync (Xamarin.Forms.Page page, System.Boolean animated) [0x00000] in <fd79b85f7e1e4bec84e0202e121dbd99>:0
  at Xamarin.Forms.Platform.GTK.Renderers.NavigationPageRenderer.OnPush (Xamarin.Forms.Page page, System.Boolean animated) [0x00000] in <fd79b85f7e1e4bec84e0202e121dbd99>:0
  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[TResult].Start[TStateMachine] (TStateMachine& stateMachine) [0x00000] in <d2ec5c92492f4d6ba8c422bdf574b786>:0
  at Xamarin.Forms.Platform.GTK.Renderers.NavigationPageRenderer.OnPush (Xamarin.Forms.Page page, System.Boolean animated) [0x00000] in <fd79b85f7e1e4bec84e0202e121dbd99>:0
  at Xamarin.Forms.Platform.GTK.Renderers.NavigationPageRenderer.PushPageAsync (Xamarin.Forms.Page page, System.Boolean animated) [0x00000] in <fd79b85f7e1e4bec84e0202e121dbd99>:0
  at Xamarin.Forms.Platform.GTK.Renderers.NavigationPageRenderer.<Init>b__24_0 (Xamarin.Forms.Page p) [0x00000] in <fd79b85f7e1e4bec84e0202e121dbd99>:0
  at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine] (TStateMachine& stateMachine) [0x00000] in <d2ec5c92492f4d6ba8c422bdf574b786>:0
  at Xamarin.Forms.Platform.GTK.Renderers.NavigationPageRenderer.<Init>b__24_0 (Xamarin.Forms.Page p) [0x00000] in <fd79b85f7e1e4bec84e0202e121dbd99>:0
  at Xamarin.Forms.Internals.EnumerableExtensions.ForEach[T] (System.Collections.Generic.IEnumerable`1[T] enumeration, System.Action`1[T] action) [0x00000] in <306fc8f0157143bda94058eb9a67dc99>:0
  at Xamarin.Forms.Platform.GTK.Renderers.NavigationPageRenderer.Init () [0x00000] in <fd79b85f7e1e4bec84e0202e121dbd99>:0
  at Xamarin.Forms.Platform.GTK.Renderers.NavigationPageRenderer.OnElementChanged (Xamarin.Forms.Platform.GTK.VisualElementChangedEventArgs e) [0x00000] in <fd79b85f7e1e4bec84e0202e121dbd99>:0
  at Xamarin.Forms.Platform.GTK.Renderers.AbstractPageRenderer`2[TWidget,TPage].SetElement (Xamarin.Forms.VisualElement element) [0x00000] in <fd79b85f7e1e4bec84e0202e121dbd99>:0
  at Xamarin.Forms.Platform.GTK.Platform.CreateRenderer (Xamarin.Forms.VisualElement element) [0x00000] in <fd79b85f7e1e4bec84e0202e121dbd99>:0
  at Xamarin.Forms.Platform.GTK.Platform.AddChild (Xamarin.Forms.Page mainPage) [0x00000] in <fd79b85f7e1e4bec84e0202e121dbd99>:0
  at Xamarin.Forms.Platform.GTK.Platform.SetPage (Xamarin.Forms.Page newRoot) [0x00000] in <fd79b85f7e1e4bec84e0202e121dbd99>:0
  at Xamarin.Forms.Platform.GTK.FormsWindow.UpdateMainPage () [0x00000] in <fd79b85f7e1e4bec84e0202e121dbd99>:0
  at Xamarin.Forms.Platform.GTK.FormsWindow.LoadApplication (Xamarin.Forms.Application application) [0x00000] in <fd79b85f7e1e4bec84e0202e121dbd99>:0
  at GWallet.Frontend.XF.Gtk.Main.main (System.String[] argv) [0x00000] in <5e0d79b7944123fea7450383b7790d5e>:0