snap: use dotnet-runtime-7.0 in MAUI snap
Since dotnet-runtime-6.0 causes the following error when
running snap:
```
Error: [/snap/gee-maui-preview/x1/usr/share/dotnet/host/fxr] does not exist
```