Backend(LN): channel closing
    - Initial close-channel implementation
    - Read more fields from the blockchain.transaction.get result
    - Log funding tx output
    - Read the Hex fields from the blockchain.transaction.get result
    - Check if output has been spent
    - WIP: Option null bug
    - Quick fix the null bug in Lightning.fs#ListAvailableChannelIds
    - Do not read Vout from blockchain.transaction.get result
    - Check if funding output is spent
    - Remove debug logging
    - Handle Negotiating channels a closing
    - Do not display closed channels
    - Remove debug logging
    - Fix underscores in matching
    - Run Fantomas on ClosedChannel.fs to fix formatting
    - Instantiate NBitcoin.Key with new to avoid warnings
    - Uncomment LightningJsonMarshalling test case
    - Remove FundingTxId field from SerializedChannel
    - Match with Lightning.ChannelStatus in DisplayLightningChannelStatus
    - Make ClosedChannel static-only
    - Remove assertions from IPEndPointJsonConverter
    - Specify exception type when trying RecvChannelMsg
    - Use DNL.Kiss df5dfa1
    - Handle multiple types of exceptions in RunClosingSignedExchange
    - Use `TransportListener` when reconnecting channel

The secret key was passed as parameter to `ActiveChannel.ConnectReestablish`.
This has been replaced by the `TransportListener`.

    - Remove FundingTransaction from ChannelInfo

That field is unused. `FundingTxId` is now used.

    - Backend(LN): handle FundingLocked during channel closing

We can receive a FundingLocked message when waiting for a Shutdown message
from the peer. We ignore the FundingLocked message and continue waiting
for the Shutdown message.

    - fix build in stockmono (to be squashed)

    Exception message for reference:

    System.AggregateException: At least one error happened. ---> System.IO.IOException: Could not read data from connection: An existing connection has been closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection has been closed by the remote host
       at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
       at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
       --- End of internal stack trace ---
       at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
       at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_1(Stream stream, IAsyncResult asyncResult)
       at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
       --- End of internal stack trace ---
       at Microsoft.FSharp.Control.AsyncResult`1.Commit() in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:Line 349.
       at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronouslyInCurrentThread[a](CancellationToken cancellationToken, FSharpAsync`1 computation) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:Line 870.
       at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronously[T](CancellationToken cancellationToken, FSharpAsync`1 computation, FSharpOption`1 timeout) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:Line 890.
       at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:Line 1153.
       at <StartupCode$GWallet-Backend>.$ClosedChannel.exchange@234-1.Invoke(Unit unitVar) in C:\Users\alexa\Desktop\geewallet\src\GWallet.Backend\UtxoCoin\Lightning\ClosedChannel.fs:Line 237.
    ---> (Internal exception #0) System.IO.IOException: Could not read data from connection: An existing connection has been closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection has been closed by the remote host
       at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
       at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
       --- End of internal stack trace ---
       at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
       at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_1(Stream stream, IAsyncResult asyncResult)
       at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)<---