Frontend: ref Nethereum.Signer to allow MonoDevelop build
Otherwise it would break with:
~/gwallet/src/GWallet.Frontend.Console/Presentation.fs(13,13): Error FS0074: The type referenced through 'Nethereum.Signer.EthECKey' is defined in an assembly that is not referenced. You must add a reference to assembly 'Nethereum.Signer'. (FS0074)

(Strangely this didn't happen with xbuild.)