Backend/Ether: handle another exception type from a server
In case the server is misconfigured, it could throw this:

System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.Exception: Some problem when connecting to https://api.myetherapi.com/eth ---> System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> Nethereum.JsonRpc.Client.RpcResponseException: This request is not supported because your node is running with state pruning. Run with --pruning=archive.
  at Nethereum.JsonRpc.Client.RpcClient.HandleRpcError (Nethereum.JsonRpc.Client.RpcMessages.RpcResponseMessage response) [0x00036] in <cd138c30e63e47479fee73b94f07264f>:0
  at Nethereum.JsonRpc.Client.RpcClient+<SendInnerRequestAync>d__12`1[T].MoveNext () [0x000c2] in <cd138c30e63e47479fee73b94f07264f>:0
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.9.1.24/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:152
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.9.1.24/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.9.1.24/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.9.1.24/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.9.1.24/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:535
  at Nethereum.JsonRpc.Client.ClientBase+<SendRequestAsync>d__4`1[T].MoveNext () [0x0014f] in <1537cb9f2aa04b178bc2725fe84a5f7e>:0
  --- End of inner exception stack trace ---
  at System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) [0x00011] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.9.1.24/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:2157
  at System.Threading.Tasks.Task.Wait (System.Int32 millisecondsTimeout, System.Threading.CancellationToken cancellationToken) [0x00043] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.9.1.24/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:3189
  at System.Threading.Tasks.Task.Wait () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.9.1.24/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:3054
  at GWallet.Backend.Ether.Server+GetConfirmedEtherBalanceInternal@168.Invoke () [0x00064] in /Users/andres/Documents/Code/gwalletFRONTEND/src/GWallet.Backend/Ether/EtherServer.fs:182
  at System.Threading.Tasks.Task`1[TResult].InnerInvoke () [0x0000f] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.9.1.24/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/threading/Tasks/Future.cs:680
  at System.Threading.Tasks.Task.Execute () [0x00010] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.9.1.24/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:2502
  --- End of inner exception stack trace ---
  at System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) [0x00011] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.9.1.24/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:2157
  at System.Threading.Tasks.Task.Wait (System.Int32 millisecondsTimeout, System.Threading.CancellationToken cancellationToken) [0x00043] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.9.1.24/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:3189
  at System.Threading.Tasks.Task.Wait (System.TimeSpan timeout) [0x00022] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.9.1.24/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:3088
  at GWallet.Backend.Ether.Server.WaitOnTask[T,R] (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] func, T arg) [0x00047] in /Users/andres/Documents/Code/gwalletFRONTEND/src/GWallet.Backend/Ether/EtherServer.fs:91
  at GWallet.Backend.Ether.Server+web3Func@190-6.Invoke (Nethereum.Web3.Web3 web3, System.String publicAddress) [0x00000] in /Users/andres/Documents/Code/gwalletFRONTEND/src/GWallet.Backend/Ether/EtherServer.fs:190
  at Microsoft.FSharp.Core.OptimizedClosures+Invoke@3252[T2,TResult,T1].Invoke (T2 u) [0x00000] in /Users/builder/data/lanes/5909/f62de472/source/xamarin-macios/external/fsharp/src/fsharp/FSharp.Core/prim-types.fs:3252
  at GWallet.Backend.Ether.Server+GetConfirmedEtherBalance@193-2.Invoke (System.String arg10) [0x00000] in /Users/andres/Documents/Code/gwalletFRONTEND/src/GWallet.Backend/Ether/EtherServer.fs:193
  at Microsoft.FSharp.Core.FSharpFunc`2[T,TResult].InvokeFast[V] (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] func, T arg1, TResult arg2) [0x0001f] in <5abd71b7dff9fae1a7450383b771bd5a>:0
  at GWallet.Backend.Ether.Server+serverFuncs@121[T,R].Invoke (GWallet.Backend.Ether.Server+SomeWeb3 web3, T arg) [0x00000] in /Users/andres/Documents/Code/gwalletFRONTEND/src/GWallet.Backend/Ether/EtherServer.fs:124
  --- End of inner exception stack trace ---
  at <StartupCode$GWallet-Backend-NetStandard>.$FaultTolerantParallelClient+clo@108-12[E,T,R].Invoke (System.Exception _arg2) [0x000c8] in /Users/andres/Documents/Code/gwalletFRONTEND/src/GWallet.Backend/FaultTolerantParallelClient.fs:114
  at Microsoft.FSharp.Control.AsyncBuilderImpl+tryWithExnA@893[a].Invoke (System.Runtime.ExceptionServices.ExceptionDispatchInfo edi) [0x00000] in /Users/builder/data/lanes/5909/f62de472/source/xamarin-macios/external/fsharp/src/fsharp/FSharp.Core/control.fs:893
  at Microsoft.FSharp.Control.AsyncBuilderImpl+callA@851[b,a].Invoke (Microsoft.FSharp.Control.AsyncParams`1[T] args) [0x0002b] in /Users/builder/data/lanes/5909/f62de472/source/xamarin-macios/external/fsharp/src/fsharp/FSharp.Core/control.fs:855
  --- End of inner exception stack trace ---
  at GWallet.Backend.Account+GetBalanceFromServerOrCache@34-4.Invoke (System.Exception _arg2) [0x00021] in /Users/andres/Documents/Code/gwalletFRONTEND/src/GWallet.Backend/Account.fs:38
  at Microsoft.FSharp.Control.AsyncBuilderImpl+tryWithExnA@893[a].Invoke (System.Runtime.ExceptionServices.ExceptionDispatchInfo edi) [0x00000] in /Users/builder/data/lanes/5909/f62de472/source/xamarin-macios/external/fsharp/src/fsharp/FSharp.Core/control.fs:893
  at Microsoft.FSharp.Control.AsyncBuilderImpl+callA@851[b,a].Invoke (Microsoft.FSharp.Control.AsyncParams`1[T] args) [0x0002b] in /Users/builder/data/lanes/5909/f62de472/source/xamarin-macios/external/fsharp/src/fsharp/FSharp.Core/control.fs:855
  --- End of inner exception stack trace ---
  at <StartupCode$GWallet-Frontend-XF>.$FrontendHelpers+DoubleCheckCompletion@61-1[T].Invoke () [0x00002] in /Users/andres/Documents/Code/gwalletFRONTEND/src/GWallet.Frontend.XF/FrontendHelpers.fs:62
  at Foundation.NSAsyncActionDispatcher.Apply () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.9.1.24/src/Xamarin.iOS/Foundation/NSAction.cs:163
  at at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.9.1.24/src/Xamarin.iOS/UIKit/UIApplication.cs:79
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x00038] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.9.1.24/src/Xamarin.iOS/UIKit/UIApplication.cs:63
  at GWalletFrontendXamForms.iOS.Main.main (System.String[] args) [0x00000] in /Users/andres/Documents/Code/gwalletFRONTEND/src/GWallet.Frontend.XamForms.iOS/AppDelegate.fs:24