Frontend.XF.*: call Xamarin.Forms.Init earlier
Xamarin.Forms.Init () was called from the entry point.
This does not work anymore and the application crashes on startup
with an exception. The reason is that the initialization of the AppSingleton
module, which happens before the entry point is executed, requires the Init()
call to be done already.

The call has been moved into a do-block inside the AppSingleton module, in
order to avoid this crash (regression caused by previous commit
c1a0ed6c12ce6736867409265c649eb095499bd4):

Unhandled Exception:
System.TypeInitializationException: The type initializer for '<StartupCode$geewallet>.$Program' threw an exception. ---> System.InvalidOperationException: You MUST call Xamarin.Forms.Init(); prior to using it.
  at Xamarin.Forms.Device.get_PlatformServices () [0x00007] in <9c7f7e2a0eb547108347ae7b430c0dfd>:0
  at Xamarin.Forms.Device.GetAssemblies () [0x00000] in <9c7f7e2a0eb547108347ae7b430c0dfd>:0
  at Xamarin.Forms.DependencyService.Initialize () [0x00021] in <9c7f7e2a0eb547108347ae7b430c0dfd>:0
  at Xamarin.Forms.DependencyService.Get[T] (Xamarin.Forms.DependencyFetchTarget fetchTarget) [0x00000] in <9c7f7e2a0eb547108347ae7b430c0dfd>:0
  at Xamarin.Forms.Application..ctor () [0x0002b] in <9c7f7e2a0eb547108347ae7b430c0dfd>:0
  at GWallet.Frontend.XF.App..ctor () [0x00000] in <5f6c7084303fdc7ea745038384706c5f>:0
  at <StartupCode$geewallet>.$Program..cctor () [0x00000] in <5f6c71dc944123fea7450383dc716c5f>:0
   --- End of inner exception stack trace ---
  at (wrapper managed-to-native) System.Object.__icall_wrapper_mono_generic_class_init(intptr)
  at GWallet.Frontend.XF.Gtk.Main.main (System.String[] argv) [0x00000] in <5f6c71dc944123fea7450383dc716c5f>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for '<StartupCode$geewallet>.$Program' threw an exception. ---> System.InvalidOperationException: You MUST call Xamarin.Forms.Init(); prior to using it.
  at Xamarin.Forms.Device.get_PlatformServices () [0x00007] in <9c7f7e2a0eb547108347ae7b430c0dfd>:0
  at Xamarin.Forms.Device.GetAssemblies () [0x00000] in <9c7f7e2a0eb547108347ae7b430c0dfd>:0
  at Xamarin.Forms.DependencyService.Initialize () [0x00021] in <9c7f7e2a0eb547108347ae7b430c0dfd>:0
  at Xamarin.Forms.DependencyService.Get[T] (Xamarin.Forms.DependencyFetchTarget fetchTarget) [0x00000] in <9c7f7e2a0eb547108347ae7b430c0dfd>:0
  at Xamarin.Forms.Application..ctor () [0x0002b] in <9c7f7e2a0eb547108347ae7b430c0dfd>:0
  at GWallet.Frontend.XF.App..ctor () [0x00000] in <5f6c7084303fdc7ea745038384706c5f>:0
  at <StartupCode$geewallet>.$Program..cctor () [0x00000] in <5f6c71dc944123fea7450383dc716c5f>:0
   --- End of inner exception stack trace ---
  at (wrapper managed-to-native) System.Object.__icall_wrapper_mono_generic_class_init(intptr)
  at GWallet.Frontend.XF.Gtk.Main.main (System.String[] argv) [0x00000] in <5f6c71dc944123fea7450383dc716c5f>:0