Fix bad handling of channel's closingTx
This commit enforces type safety on functions like
CheckForClosingTx, FindRemoteForceClose and etc to fix issues
like mishandling of forgotten (e.g. not saved due to crash)
MutualCloseTXs as ForceCloseTXs, which could result in this
other crash:

System.Exception: invalid commitment tx for creating recovery tx: invalid lock time and sequence for commitment tx (locktime = Height : 0, sequence = 4294967295)
   at <StartupCode$GWallet-Backend>.$Node.CreateRecoveryTxForRemoteForceClose@740-7.Invoke(FeeRatePerKw _arg8) in C:\Users\Afshin Arani\source\repos\geewallet\src\GWallet.Backend\UtxoCoin\Lightning\Node.fs:line 752
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 416
   at <StartupCode$GWallet-Backend>.$Node.CreateRecoveryTxForRemoteForceClose@738-5.Invoke(AsyncActivation`1 ctxt) in C:\Users\Afshin Arani\source\repos\geewallet\src\GWallet.Backend\UtxoCoin\Lightning\Node.fs:line 738
   at <StartupCode$GWallet-Backend>.$FeeEstimator.Create@21-6.Invoke(AsyncActivation`1 ctxt) in C:\Users\Afshin Arani\source\repos\geewallet\src\GWallet.Backend\UtxoCoin\Lightning\FeeEstimator.fs:line 21
   at <StartupCode$GWallet-Backend>.$FaultTolerantParallelClient.QueryInternal@721-2.Invoke(AsyncActivation`1 ctxt) in C:\Users\Afshin Arani\source\repos\geewallet\src\GWallet.Backend\FaultTolerantParallelClient.fs:line 721
   at <StartupCode$GWallet-Backend>.$FaultTolerantParallelClient.clo@558-51.Invoke(AsyncActivation`1 ctxt) in C:\Users\Afshin Arani\source\repos\geewallet\src\GWallet.Backend\FaultTolerantParallelClient.fs:line 558
   at <StartupCode$GWallet-Backend>.$FaultTolerantParallelClient.jobWithCancellation@506-3.Invoke(AsyncActivation`1 ctxt) in C:\Users\Afshin Arani\source\repos\geewallet\src\GWallet.Backend\FaultTolerantParallelClient.fs:line 506
   at <StartupCode$GWallet-Backend>.$FaultTolerantParallelClient.clo@380-30.Invoke(AsyncActivation`1 ctxt) in C:\Users\Afshin Arani\source\repos\geewallet\src\GWallet.Backend\FaultTolerantParallelClient.fs:line 380
   at <StartupCode$GWallet-Backend>.$FaultTolerantParallelClient.WhenAny@118-7.Invoke(AsyncActivation`1 ctxt) in C:\Users\Afshin Arani\source\repos\geewallet\src\GWallet.Backend\FaultTolerantParallelClient.fs:line 118
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 109
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.FSharp.Control.AsyncResult`1.Commit() in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 349
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronouslyInCurrentThread[a](CancellationToken cancellationToken, FSharpAsync`1 computation) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 870
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronously[T](CancellationToken cancellationToken, FSharpAsync`1 computation, FSharpOption`1 timeout) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 890
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 1153
   at Program.ProgramMainLoop[a]() in C:\Users\Afshin Arani\source\repos\geewallet\src\GWallet.Frontend.Console\Program.fs:line 401
   at Program.NormalStartWithNoParameters() in C:\Users\Afshin Arani\source\repos\geewallet\src\GWallet.Frontend.Console\Program.fs:line 417
System.Exception: invalid commitment tx for creating recovery tx: invalid lock time and sequence for commitment tx (locktime = Height : 0, sequence = 4294967295)
   at GWallet.Backend.Infrastructure.Report(Exception ex, ErrorLevel _arg1) in C:\Users\Afshin Arani\source\repos\geewallet\src\GWallet.Backend\Infrastructure.fs:line 131
   at GWallet.Backend.Infrastructure.LogOrReportCrash(Exception ex) in C:\Users\Afshin Arani\source\repos\geewallet\src\GWallet.Backend\Infrastructure.fs:line 148
   at Program.NormalStartWithNoParameters() in C:\Users\Afshin Arani\source\repos\geewallet\src\GWallet.Frontend.Console\Program.fs:line 421
   at Program.main(String[] argv) in C:\Users\Afshin Arani\source\repos\geewallet\src\GWallet.Frontend.Console\Program.fs:line 439

Co-authored-by: Andrew Cann <shum@canndrew.org>