Backend/Marshalling: double-protection against weird null
Strangely enough, I've got this exception when importing a transaction
in my cold storage device: [1]. If I look at the code, this should not
happen, therefore I'm adding an extra stupid try-with block, and switching
the order of the parameters passed to Object.ReferenceEquals() as a
paranoid measure.

[1] Introduce a file name to load the unsigned transaction: 2ku.json
System.NullReferenceException: Object reference not set to an instance of an object
  at GWallet.Backend.Marshalling.ExtractType (System.String json) [0x00006] in <60a5eb435e45f38ba745038343eba560>:0
  at GWallet.Backend.Account.ImportUnsignedTransactionFromJson (System.String json) [0x00000] in <60a5eb435e45f38ba745038343eba560>:0
  at GWallet.Backend.Account.LoadUnsignedTransactionFromFile (System.String filePath) [0x00007] in <60a5eb435e45f38ba745038343eba560>:0
  at Program.SignOffPayment () [0x00011] in <60a5eb48706f857da745038348eba560>:0
  at Program.PerformOperation (System.Int32 numAccounts) [0x0013b] in <60a5eb48706f857da745038348eba560>:0
  at Program.ProgramMainLoop[a] () [0x00052] in <60a5eb48706f857da745038348eba560>:0
  at Program.NormalStartWithNoParameters () [0x00007] in <60a5eb48706f857da745038348eba560>:0
System.NullReferenceException: Object reference not set to an instance of an object
  at GWallet.Backend.Infrastructure.Report (System.Exception ex, SharpRaven.Data.ErrorLevel _arg1) [0x00019] in <60a5eb435e45f38ba745038343eba560>:0
  at GWallet.Backend.Infrastructure.LogOrReportCrash (System.Exception ex) [0x00000] in <60a5eb435e45f38ba745038343eba560>:0
  at Program.NormalStartWithNoParameters () [0x00017] in <60a5eb48706f857da745038348eba560>:0
  at Program.main (System.String[] argv) [0x0002b] in <60a5eb48706f857da745038348eba560>:0
exception inside UnhandledException handler: (null) assembly:/usr/lib/mono/4.5/mscorlib.dll type:NullReferenceException member:(null)

[ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
  at GWallet.Backend.Infrastructure.Report (System.Exception ex, SharpRaven.Data.ErrorLevel _arg1) [0x00019] in <60a5eb435e45f38ba745038343eba560>:0
  at GWallet.Backend.Infrastructure.LogOrReportCrash (System.Exception ex) [0x00000] in <60a5eb435e45f38ba745038343eba560>:0
  at Program.NormalStartWithNoParameters () [0x00017] in <60a5eb48706f857da745038348eba560>:0
  at Program.main (System.String[] argv) [0x0002b] in <60a5eb48706f857da745038348eba560>:0
  at GWallet.Backend.Infrastructure.Report (System.Exception ex, SharpRaven.Data.ErrorLevel _arg1) [0x00019] in <60a5eb435e45f38ba745038343eba560>:0
  at GWallet.Backend.Infrastructure.LogOrReportCrash (System.Exception ex) [0x00000] in <60a5eb435e45f38ba745038343eba560>:0
  at GWallet.Backend.Infrastructure.OnUnhandledException (System.Object _arg1, System.UnhandledExceptionEventArgs args) [0x0000e] in <60a5eb435e45f38ba745038343eba560>:0
  at GWallet.Backend.Infrastructure+SetupExceptionHook@179-4.Invoke (System.Object delegateArg0, System.UnhandledExceptionEventArgs delegateArg1) [0x00000] in <60a5eb435e45f38ba745038343eba560>:0
~