Backend: unbreak Frontend.Console when run on Windows
When trying to fix the launch of the app in UWP [1], we broke
Frontend.Console when run on Windows [3].

Being run on Windows OS doesn't necessarily mean that we're
running in UWP platform! We will have to fix this properly in
the tests too, see [2].

This bug was reported by Janus Troelsen <ysangkok@gmail.com>

[1] f07721d101d80884f00e1a86db4759e493988e22
[2] 97c4036c093e6ef4f2f2dd6a30da7114c2e017ae
[3] It was throwing this exception:
Xamarin.Essentials.NotImplementedInReferenceAssemblyException: This functionality is not implemented in the portable version of this assembly. You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.
   at Xamarin.Essentials.FileSystem.get_PlatformAppDataDirectory() in C:\agent\_work\69\s\Xamarin.Essentials\FileSystem\FileSystem.netstandard.cs:line 12
   at Xamarin.Essentials.FileSystem.get_AppDataDirectory() in C:\agent\_work\69\s\Xamarin.Essentials\FileSystem\FileSystem.shared.cs:line 12
   at GWallet.Backend.Config.GetConfigDirForThisProgram() in C:\Users\knoct\Source\Repos\geewallet\src\GWallet.Backend\Config.fs:line 98
   at GWallet.Backend.Config.GetConfigDirForAccounts() in C:\Users\knoct\Source\Repos\geewallet\src\GWallet.Backend\Config.fs:line 106
   at GWallet.Backend.Config.GetConfigDir(Currency currency, AccountKind accountKind) in C:\Users\knoct\Source\Repos\geewallet\src\GWallet.Backend\Config.fs:line 113
   at GWallet.Backend.Config.GetAccountFiles@131.GenerateNext(IEnumerable`1& next) in C:\Users\knoct\Source\Repos\geewallet\src\GWallet.Backend\Config.fs:line 132
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()
   at GWallet.Backend.Account.GetAllActiveAccounts@72.GenerateNext(IEnumerable`1& next) in C:\Users\knoct\Source\Repos\geewallet\src\GWallet.Backend\Account.fs:line 73
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at Microsoft.FSharp.Collections.ListModule.OfSeq[T](IEnumerable`1 source)
   at GWallet.Backend.Account.GetAllActiveAccounts() in C:\Users\knoct\Source\Repos\geewallet\src\GWallet.Backend\Account.fs:line 71
   at Program.ProgramMainLoop[a]() in C:\Users\knoct\Source\Repos\geewallet\src\GWallet.Frontend.Console\Program.fs:line 291
   at Program.NormalStartWithNoParameters() in C:\Users\knoct\Source\Repos\geewallet\src\GWallet.Frontend.Console\Program.fs:line 304
Xamarin.Essentials.NotImplementedInReferenceAssemblyException: This functionality is not implemented in the portable version of this assembly. You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.
   at GWallet.Backend.Infrastructure.Report[a](Exception ex) in C:\Users\knoct\Source\Repos\geewallet\src\GWallet.Backend\Infrastructure.fs:line 22
   at Program.NormalStartWithNoParameters() in C:\Users\knoct\Source\Repos\geewallet\src\GWallet.Frontend.Console\Program.fs:line 308
   at Program.main(String[] argv) in C:\Users\knoct\Source\Repos\geewallet\src\GWallet.Frontend.Console\Program.fs:line 326

Unhandled Exception: Xamarin.Essentials.NotImplementedInReferenceAssemblyException: This functionality is not implemented in the portable version of this assembly. You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.
   at GWallet.Backend.Infrastructure.Report[a](Exception ex) in C:\Users\knoct\Source\Repos\geewallet\src\GWallet.Backend\Infrastructure.fs:line 22
   at GWallet.Backend.Infrastructure.OnUnhandledException[a](Object sender, UnhandledExceptionEventArgs args) in C:\Users\knoct\Source\Repos\geewallet\src\GWallet.Backend\Infrastructure.fs:line 28
   at GWallet.Backend.Infrastructure.SetupSentryHook@31-4.Invoke(Object delegateArg0, UnhandledExceptionEventArgs delegateArg1) in C:\Users\knoct\Source\Repos\geewallet\src\GWallet.Backend\Infrastructure.fs:line 31