build: print nuget version upon successful or failed build
This is because suddenly today the nuget.exe version
downloaded by xbuild started failing with an exception[1],
which I will have to report. But I need to know the
version first.

[1] 	Target RestoreSolutions:
		Restoring /builds/knocte/gwallet/gwallet.sln...
		Executing: mono ".nuget/nuget.exe" Restore "/builds/knocte/gwallet/gwallet.sln" -DisableParallelProcessing
		Unhandled Exception:
		System.MissingMethodException: Method 'Array.Empty' not found.
		  at NuGet.Common.ExceptionUtilities.DisplayMessage (System.Exception exception, Boolean indent) <0x419bea20 + 0x000af> in <filename unknown>:0
		  at NuGet.Common.ExceptionUtilities.DisplayMessage (System.Exception exception) <0x419be9f0 + 0x00013> in <filename unknown>:0
		  at NuGet.Common.ExceptionUtilities.LogException (System.Exception ex, ILogger logger, Boolean logStackAsError) <0x419be6e0 + 0x00133> in <filename unknown>:0
		  at NuGet.CommandLine.Program.MainCore (System.String workingDirectory, System.String[] args) <0x41995860 + 0x008db> in <filename unknown>:0
		  at NuGet.CommandLine.Program.Main (System.String[] args) <0x41991d50 + 0x00037> in <filename unknown>:0
		[ERROR] FATAL UNHANDLED EXCEPTION: System.MissingMethodException: Method 'Array.Empty' not found.
		  at NuGet.Common.ExceptionUtilities.DisplayMessage (System.Exception exception, Boolean indent) <0x419bea20 + 0x000af> in <filename unknown>:0
		  at NuGet.Common.ExceptionUtilities.DisplayMessage (System.Exception exception) <0x419be9f0 + 0x00013> in <filename unknown>:0
		  at NuGet.Common.ExceptionUtilities.LogException (System.Exception ex, ILogger logger, Boolean logStackAsError) <0x419be6e0 + 0x00133> in <filename unknown>:0
		  at NuGet.CommandLine.Program.MainCore (System.String workingDirectory, System.String[] args) <0x41995860 + 0x008db> in <filename unknown>:0
		  at NuGet.CommandLine.Program.Main (System.String[] args) <0x41991d50 + 0x00037> in <filename unknown>:0
/builds/knocte/gwallet/NuGet.Restore.targets: error : Command 'mono ".nuget/nuget.exe" Restore "/builds/knocte/gwallet/gwallet.sln" -DisableParallelProcessing ' exited with code: 1.
	Task "Exec" execution -- FAILED
	Done building target "RestoreSolutions" in project "/builds/knocte/gwallet/gwallet.sln".-- FAILED
Done building project "/builds/knocte/gwallet/gwallet.sln".-- FAILED

Build FAILED.
Errors:

/builds/knocte/gwallet/gwallet.sln (default targets) ->
/builds/knocte/gwallet/NuGet.Restore.targets (RestoreSolutions target) ->

	/builds/knocte/gwallet/NuGet.Restore.targets: error : Command 'mono ".nuget/nuget.exe" Restore "/builds/knocte/gwallet/gwallet.sln" -DisableParallelProcessing ' exited with code: 1.

	 0 Warning(s)
	 1 Error(s)

Time Elapsed 00:00:01.4645490
make: *** [all] Error 1
Makefile:2: recipe for target 'all' failed

real	0m13.489s
user	0m10.924s
sys	0m1.976s