Frontend.XF.UWP: upgrade target platform version
This fixes the following warning:
Xamarin.Forms recommends TargetPlatformVersion >= 10.0.17763.0 (current project is 16299)

And the following compilation error:
CS0234	The type or namespace name 'IXamlType2' does not exist in the namespace 'Windows.UI.Xaml.Markup' (are you missing an assembly reference?)