Backend.Tests: fix build (xbuild)
xbuild (as opposed to MonoDevelop build) could throw this error somehow:

Errors:

/home/andres/Documents/gwallet/gwallet.sln (default targets) ->
(Build target) ->
/home/andres/Documents/gwallet/src/GWallet.Backend.Tests/GWallet.Backend.Tests.fsproj (default targets) ->
/usr/lib/mono/4.5/Microsoft.FSharp.Targets (CoreCompile target) ->

	/home/andres/Documents/gwallet/src/GWallet.Backend.Tests/Serialization.fs(17,13): error FS0074: The type referenced through 'Nethereum.Signer.EthECKey' is defined in an assembly that is not referenced. You must add a reference to assembly 'Nethereum.Signer'.

	 8 Warning(s)
	 1 Error(s)