Revert all changes from v212 to v214 (except the version changes)
It seems that geewallet's snap package is crashing with this[1] so
I'm reverting everything done in this release until I figure out what's
wrong.

[1] Could not load signature of GWallet.Backend.Ether.Account:get_KeyStoreService due to: Could not load file or assembly 'Nethereum.KeyStore, Version=3.0.0.0, Culture=neutral, PublicKeyToken=8768a594786aba4e' or one of its dependencies.
System.TypeLoadException: Failure has occurred while loading a type.
  at GWallet.Backend.Ether.Account+GetAccountFromFile@45-4.Invoke (GWallet.Backend.FileRepresentation accountFile) [0x00000] in <5eecda64be1c2694a745038364daec5e>:0
  at GWallet.Backend.BaseAccount..ctor (GWallet.Backend.Currency currency, GWallet.Backend.FileRepresentation accountFile, Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] fromAccountFileToPublicAddress) [0x00016] in <5eecda64be1c2694a745038364daec5e>:0
  at GWallet.Backend.NormalAccount..ctor (GWallet.Backend.Currency currency, GWallet.Backend.FileRepresentation accountFile, Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] fromAccountFileToPublicAddress) [0x00000] in <5eecda64be1c2694a745038364daec5e>:0
  at GWallet.Backend.Ether.Account.GetAccountFromFile (GWallet.Backend.FileRepresentation accountFile, GWallet.Backend.Currency currency, GWallet.Backend.AccountKind kind) [0x00075] in <5eecda64be1c2694a745038364daec5e>:0
  at GWallet.Backend.Account.GetAccountFromFile (GWallet.Backend.FileRepresentation accountFile, GWallet.Backend.Currency currency, GWallet.Backend.AccountKind kind) [0x00026] in <5eecda64be1c2694a745038364daec5e>:0
  at GWallet.Backend.Account+GetAllActiveAccounts@83.GenerateNext (System.Collections.Generic.IEnumerable`1[GWallet.Backend.IAccount]& next) [0x00125] in <5eecda64be1c2694a745038364daec5e>:0
  at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1[T].MoveNextImpl () [0x00016] in <039b17603f7a807e0eeaa652dc64c784>:0
  at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1[T].System-Collections-IEnumerator-MoveNext () [0x00000] in <039b17603f7a807e0eeaa652dc64c784>:0
  at System.Linq.Enumerable+<OfTypeIterator>d__32`1[TResult].MoveNext () [0x00067] in <7bb3b9b46f014210b38257ba21db03a8>:0
  at Microsoft.FSharp.Collections.SeqModule.ToList[T] (System.Collections.Generic.IEnumerable`1[T] source) [0x0005e] in <039b17603f7a807e0eeaa652dc64c784>:0
  at GWallet.Frontend.XF.LoadingPage..ctor (GWallet.Frontend.XF.FrontendHelpers+IGlobalAppState state, System.Boolean showLogoFirst) [0x000ad] in <5eecda6a303fdc7ea74503836adaec5e>:0
  at GWallet.Frontend.XF.Initialization.LandingPage () [0x00026] in <5eecda6a303fdc7ea74503836adaec5e>:0
  at GWallet.Frontend.XF.App..ctor () [0x00008] in <5eecda6a303fdc7ea74503836adaec5e>:0
  at GWallet.Frontend.XF.Gtk.Main.main (System.String[] argv) [0x00022] in <5eecda6f944123fea74503836fdaec5e>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Failure has occurred while loading a type.
  at GWallet.Backend.Ether.Account+GetAccountFromFile@45-4.Invoke (GWallet.Backend.FileRepresentation accountFile) [0x00000] in <5eecda64be1c2694a745038364daec5e>:0
  at GWallet.Backend.BaseAccount..ctor (GWallet.Backend.Currency currency, GWallet.Backend.FileRepresentation accountFile, Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] fromAccountFileToPublicAddress) [0x00016] in <5eecda64be1c2694a745038364daec5e>:0
  at GWallet.Backend.NormalAccount..ctor (GWallet.Backend.Currency currency, GWallet.Backend.FileRepresentation accountFile, Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] fromAccountFileToPublicAddress) [0x00000] in <5eecda64be1c2694a745038364daec5e>:0
  at GWallet.Backend.Ether.Account.GetAccountFromFile (GWallet.Backend.FileRepresentation accountFile, GWallet.Backend.Currency currency, GWallet.Backend.AccountKind kind) [0x00075] in <5eecda64be1c2694a745038364daec5e>:0
  at GWallet.Backend.Account.GetAccountFromFile (GWallet.Backend.FileRepresentation accountFile, GWallet.Backend.Currency currency, GWallet.Backend.AccountKind kind) [0x00026] in <5eecda64be1c2694a745038364daec5e>:0
  at GWallet.Backend.Account+GetAllActiveAccounts@83.GenerateNext (System.Collections.Generic.IEnumerable`1[GWallet.Backend.IAccount]& next) [0x00125] in <5eecda64be1c2694a745038364daec5e>:0
  at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1[T].MoveNextImpl () [0x00016] in <039b17603f7a807e0eeaa652dc64c784>:0
  at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1[T].System-Collections-IEnumerator-MoveNext () [0x00000] in <039b17603f7a807e0eeaa652dc64c784>:0
  at System.Linq.Enumerable+<OfTypeIterator>d__32`1[TResult].MoveNext () [0x00067] in <7bb3b9b46f014210b38257ba21db03a8>:0
  at Microsoft.FSharp.Collections.SeqModule.ToList[T] (System.Collections.Generic.IEnumerable`1[T] source) [0x0005e] in <039b17603f7a807e0eeaa652dc64c784>:0
  at GWallet.Frontend.XF.LoadingPage..ctor (GWallet.Frontend.XF.FrontendHelpers+IGlobalAppState state, System.Boolean showLogoFirst) [0x000ad] in <5eecda6a303fdc7ea74503836adaec5e>:0
  at GWallet.Frontend.XF.Initialization.LandingPage () [0x00026] in <5eecda6a303fdc7ea74503836adaec5e>:0
  at GWallet.Frontend.XF.App..ctor () [0x00008] in <5eecda6a303fdc7ea74503836adaec5e>:0
  at GWallet.Frontend.XF.Gtk.Main.main (System.String[] argv) [0x00022] in <5eecda6f944123fea74503836fdaec5e>:0