Backend: fix possible race condition around task cancellation
Instead of subscribing to the event after we convert the jobs into
running tasks, we create the jobs first, then subscribe, then launch
the tasks. This should fix this bug:
https://sentry.io/organizations/nblockchain/issues/1343971578/

Whose exception details are:
AggregateException: One or more errors occurred. (Cancellation at first-balances querying)
  Module "GWallet.Frontend.XF.FrontendHelpers+MaybeCrash@213", line 0, col 0, in Invoke
    Void Invoke()
  Module "Java.Lang.Thread+RunnableImplementor", line 8, col 0, in Run
    Void Run()
  Module "Java.Lang.IRunnableInvoker", line 9, col 0, in n_Run
    Void n_Run(IntPtr, IntPtr)
  Module "(unknown)", col 0, in (unknown)
InvalidOperationException: Cancellation at first-balances querying
  Module "<StartupCode$GWallet-Frontend-XF>.$LoadingPage.xaml", line 35, col 0, in catchHandler@1-8
    Microsoft.FSharp.Control.FSharpAsync`1[Microsoft.FSharp.Core.Unit] catchHandler@1-8(System.Exception)
  Module "<StartupCode$GWallet-Frontend-XF>.$LoadingPage.xaml+populateGrid@133-7", line 0, col 0, in Invoke
    Microsoft.FSharp.Core.FSharpOption`1[Microsoft.FSharp.Control.FSharpAsync`1[Microsoft.FSharp.Core.Unit]] Invoke(System.Exception)
  Module "Microsoft.FSharp.Control.AsyncPrimitives", line 12, col 0, in CallFilterThenInvoke
    Microsoft.FSharp.Control.AsyncReturn CallFilterThenInvoke[Unit](Microsoft.FSharp.Control.AsyncActivation`1[Microsoft.FSharp.Core.Unit], Microsoft.FSharp.Core.FSharpFunc`2[System.Exception,Microsoft.FSharp.Core.FSharpOption`1[Microsoft.FSharp.Control.FSharpAsync`1[Microsoft.FSharp.Core.Unit]]], System.Runtime.ExceptionServices.ExceptionDispatchInfo)
  Module "Microsoft.FSharp.Control.AsyncPrimitives+TryWith@526[[Microsoft.FSharp.Core.Unit, FSharp.Core, Version=4.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]]", line 40, col 0, in Invoke
    Microsoft.FSharp.Control.AsyncReturn Invoke(System.Runtime.ExceptionServices.ExceptionDispatchInfo)
  Module "Microsoft.FSharp.Control.AsyncPrimitives+Bind@495-1[[Microsoft.FSharp.Control.AsyncResult`1[[GWallet.Frontend.XF.BalanceState[], GWallet.Frontend.XF, Version=0.4.2.160, Culture=neutral, PublicKeyToken=null]], FSharp.Core, Version=4.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a],[GWallet.Frontend.XF.BalanceState[], GWallet.Frontend.XF, Version=0.4.2.160, Culture=neutral, PublicKeyToken=null]]", line 0, col 0, in Invoke
    Microsoft.FSharp.Control.AsyncReturn Invoke(Microsoft.FSharp.Control.AsyncResult`1[GWallet.Frontend.XF.BalanceState[]])
  Module "Microsoft.FSharp.Control.Trampoline", line 32, col 0, in Execute
    Microsoft.FSharp.Control.AsyncReturn Execute(Microsoft.FSharp.Core.FSharpFunc`2[Microsoft.FSharp.Core.Unit,Microsoft.FSharp.Control.AsyncReturn])
InvalidOperationException: Cancellation at normal-account first-query
  Module "<StartupCode$GWallet-Frontend-XF>.$LoadingPage.xaml", line 35, col 0, in catchHandler@1-6
    Microsoft.FSharp.Control.FSharpAsync`1[GWallet.Frontend.XF.BalanceState[]] catchHandler@1-6(System.Exception)
  Module "<StartupCode$GWallet-Frontend-XF>.$LoadingPage.xaml+allNormalAccountBalancesJobAugmented@103-7", line 0, col 0, in Invoke
    Microsoft.FSharp.Core.FSharpOption`1[Microsoft.FSharp.Control.FSharpAsync`1[GWallet.Frontend.XF.BalanceState[]]] Invoke(System.Exception)
  Module "Microsoft.FSharp.Control.AsyncPrimitives", line 12, col 0, in CallFilterThenInvoke
    Microsoft.FSharp.Control.AsyncReturn CallFilterThenInvoke[BalanceState[]](Microsoft.FSharp.Control.AsyncActivation`1[GWallet.Frontend.XF.BalanceState[]], Microsoft.FSharp.Core.FSharpFunc`2[System.Exception,Microsoft.FSharp.Core.FSharpOption`1[Microsoft.FSharp.Control.FSharpAsync`1[GWallet.Frontend.XF.BalanceState[]]]], System.Runtime.ExceptionServices.ExceptionDispatchInfo)
  Module "Microsoft.FSharp.Control.AsyncPrimitives+TryWith@526[[GWallet.Frontend.XF.BalanceState[], GWallet.Frontend.XF, Version=0.4.2.160, Culture=neutral, PublicKeyToken=null]]", line 40, col 0, in Invoke
    Microsoft.FSharp.Control.AsyncReturn Invoke(System.Runtime.ExceptionServices.ExceptionDispatchInfo)
  Module "Microsoft.FSharp.Control.Trampoline", line 32, col 0, in Execute
    Microsoft.FSharp.Control.AsyncReturn Execute(Microsoft.FSharp.Core.FSharpFunc`2[Microsoft.FSharp.Core.Unit,Microsoft.FSharp.Control.AsyncReturn])
TaskCanceledException: Found canceled when about subscribe to cancellation
  Module "GWallet.Backend.Ether.Account", line 28, col 0, in catchHandler@1-12
    Microsoft.FSharp.Control.FSharpAsync`1[Microsoft.FSharp.Core.FSharpOption`1[System.Decimal]] catchHandler@1-12(System.Exception)
  Module "GWallet.Backend.Ether.Account+GetBalanceFromServer@59-7", line 0, col 0, in Invoke
    Microsoft.FSharp.Core.FSharpOption`1[Microsoft.FSharp.Control.FSharpAsync`1[Microsoft.FSharp.Core.FSharpOption`1[System.Decimal]]] Invoke(System.Exception)
  Module "Microsoft.FSharp.Control.AsyncPrimitives", line 12, col 0, in CallFilterThenInvoke
    Microsoft.FSharp.Control.AsyncReturn CallFilterThenInvoke[FSharpOption`1](Microsoft.FSharp.Control.AsyncActivation`1[Microsoft.FSharp.Core.FSharpOption`1[System.Decimal]], Microsoft.FSharp.Core.FSharpFunc`2[System.Exception,Microsoft.FSharp.Core.FSharpOption`1[Microsoft.FSharp.Control.FSharpAsync`1[Microsoft.FSharp.Core.FSharpOption`1[System.Decimal]]]], System.Runtime.ExceptionServices.ExceptionDispatchInfo)
  Module "Microsoft.FSharp.Control.AsyncPrimitives+TryWith@526[[Microsoft.FSharp.Core.FSharpOption`1[[System.Decimal, mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], FSharp.Core, Version=4.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]]", line 40, col 0, in Invoke
    Microsoft.FSharp.Control.AsyncReturn Invoke(System.Runtime.ExceptionServices.ExceptionDispatchInfo)
  Module "Microsoft.FSharp.Control.Trampoline", line 32, col 0, in Execute
    Microsoft.FSharp.Control.AsyncReturn Execute(Microsoft.FSharp.Core.FSharpFunc`2[Microsoft.FSharp.Core.Unit,Microsoft.FSharp.Control.AsyncReturn])