Fix 'crypto.dll' load exception (regression at runtime)
After previous commit that fixes the build in Linux, running the frontend
Console app was throwing this exception at runtime (which I assume would
be thrown as well in Windows): [0].

Thing is, we had to remove BouncyCastle Portable from the Nuget package list
in previous commit, otherwise nuget couldn't restore the packages (since
apparently the latest version of BouncyCastle Portable requires a too new
nuget version...). So to workaround the now missing dependency, we add the
normal (nonPortable) BouncyCastle nuget dependency, and copy it to the name
that the .dll has in its Portable version in an AfterBuild MSBuild target.

[0] Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'crypto, Version=1.8.1.0, Culture=neutral, PublicKeyToken=0e99375e54769942' or one of its dependencies.
File name: 'crypto, Version=1.8.1.0, Culture=neutral, PublicKeyToken=0e99375e54769942'
  at Nethereum.KeyStore.KeyStorePbkdf2Service..ctor () <0x416e35d0 + 0x0000f> in <filename unknown>:0
  at Nethereum.KeyStore.KeyStoreService..ctor () <0x416e3470 + 0x00083> in <filename unknown>:0
  at GWallet.Backend.NormalAccount.get_KeyStoreService () <0x416e3300 + 0x00027> in <filename unknown>:0
  at GWallet.Backend.NormalAccount..ctor (Currency currency, System.String json) <0x416de4f0 + 0x000cb> in <filename unknown>:0
  at GWallet.Backend.Config+GetAllAccounts@43.GenerateNext (IEnumerable`1& next) <0x416dd560 + 0x001df> in <filename unknown>:0
  at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1[T].MoveNextImpl () <0x416dabb0 + 0x00069> in <filename unknown>:0
  at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1[T].System-Collections-IEnumerator-MoveNext () <0x416dab80 + 0x00017> in <filename unknown>:0
  at GWallet.Backend.AccountApi+GetAllAccounts@67-1.GenerateNext (IEnumerable`1& next) <0x416dae10 + 0x0023a> in <filename unknown>:0
  at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1[T].MoveNextImpl () <0x416dabb0 + 0x00069> in <filename unknown>:0
  at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1[T].System-Collections-IEnumerator-MoveNext () <0x416dab80 + 0x00017> in <filename unknown>:0
  at System.Linq.Enumerable.Any[TSource] (IEnumerable`1 source) <0x416da9a0 + 0x00052> in <filename unknown>:0
  at Program.DisplayAccountStatuses (WhichAccount whichAccount) <0x416d73d0 + 0x0010b> in <filename unknown>:0
  at Program.ProgramMainLoop[a] () <0x416d7000 + 0x0002b> in <filename unknown>:0
  at Program.main (System.String[] argv) <0x416d6d50 + 0x0002b> in <filename unknown>:0