Frontend.Console: fix dll-version mismatch crash on Windows
It seems that the upgrade of Newtonsoft.Json from 9.x to 10.x [1]
caused a regression [4] which was only reproducible on Windows
(didn't get it in Mac or Linux), which is probably caused by
the fact that even if Nethereum.JsonRpc.RpcClient 2.0.1 correctly
depends [2] on Newtonsoft.Json (>= 10.0.3), it also depends on
EdjCase.JsonRpc.Client (>= 1.3.1) which itself depends on an
earlier version of Newtonsoft (9) [3].

Also, add a FIXME with regards to this weird EdjCase dependencies.

[1] https://gitlab.com/knocte/gwallet/commit/b5c29d3ef397776cca794a05c6e91fdc578265d0

[2] https://www.nuget.org/packages/Nethereum.JsonRpc.RpcClient/2.0.1

[3] https://www.nuget.org/packages/EdjCase.JsonRpc.Client/1.3.1

[4] System.TypeInitializationException: The type initializer for '<StartupCode$GWallet-Backend>.$EtherServer' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Nethereum.JsonRpc.Client.RpcClient..ctor(Uri baseUrl, AuthenticationHeaderValue authHeaderValue, JsonSerializerSettings jsonSerializerSettings)
   at Nethereum.Web3.Web3.IntialiseDefaultRpcClient(String url)
   at Nethereum.Web3.Web3..ctor(String url)
   at <StartupCode$GWallet-Backend>.$EtherServer..cctor() in C:\Users\andres\Documents\Code\gwalletMASTER\src\GWallet.Backend\Ether\EtherServer.fs:line 52
   --- End of inner exception stack trace ---
   at GWallet.Backend.Ether.Server.get_ethWeb3Infura()
   at GWallet.Backend.Ether.Server.GetWeb3Servers(Currency currency) in C:\Users\andres\Documents\Code\gwalletMASTER\src\GWallet.Backend\Ether\EtherServer.fs:line 61
   at GWallet.Backend.Ether.Server.PlumbingCall[T,R](Currency currency, T arg, FSharpFunc`2 web3Func) in C:\Users\andres\Documents\Code\gwalletMASTER\src\GWallet.Backend\Ether\EtherServer.fs:line 95
   at GWallet.Backend.Ether.Server.GetBalance(Currency currency, String address) in C:\Users\andres\Documents\Code\gwalletMASTER\src\GWallet.Backend\Ether\EtherServer.fs:line 109
   at GWallet.Backend.Ether.Account.GetBalance(IAccount account) in C:\Users\andres\Documents\Code\gwalletMASTER\src\GWallet.Backend\Ether\EtherAccount.fs:line 43
   at GWallet.Backend.Account.GetBalanceFromServerOrCache(IAccount account, Boolean confirmed) in C:\Users\andres\Documents\Code\gwalletMASTER\src\GWallet.Backend\Account.fs:line 26
   at GWallet.Backend.Account.GetBalance(IAccount account) in C:\Users\andres\Documents\Code\gwalletMASTER\src\GWallet.Backend\Account.fs:line 39
   at GWallet.Frontend.Console.UserInteraction.DisplayAccountStatus(Int32 accountNumber, IAccount account) in C:\Users\andres\Documents\Code\gwalletMASTER\src\GWallet.Frontend.Console\UserInteraction.fs:line 164
   at GWallet.Frontend.Console.UserInteraction.displayAllAndSumBalance@188.Invoke(IEnumerable`1 accounts, Int32 currentIndex, FSharpMap`2 currentSumMap) in C:\Users\andres\Documents\Code\gwalletMASTER\src\GWallet.Frontend.Console\UserInteraction.fs:line 189
   at GWallet.Frontend.Console.UserInteraction.DisplayAccountStatuses(WhichAccount whichAccount) in C:\Users\andres\Documents\Code\gwalletMASTER\src\GWallet.Frontend.Console\UserInteraction.fs:line 252
   at Program.ProgramMainLoop[a]() in C:\Users\andres\Documents\Code\gwalletMASTER\src\GWallet.Frontend.Console\Program.fs:line 250
   at Program.main(String[] argv) in C:\Users\andres\Documents\Code\gwalletMASTER\src\GWallet.Frontend.Console\Program.fs:line 262
System.TypeInitializationException: The type initializer for '<StartupCode$GWallet-Backend>.$EtherServer' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Nethereum.JsonRpc.Client.RpcClient..ctor(Uri baseUrl, AuthenticationHeaderValue authHeaderValue, JsonSerializerSettings jsonSerializerSettings)
   at Nethereum.Web3.Web3.IntialiseDefaultRpcClient(String url)
   at Nethereum.Web3.Web3..ctor(String url)
   at <StartupCode$GWallet-Backend>.$EtherServer..cctor() in C:\Users\andres\Documents\Code\gwalletMASTER\src\GWallet.Backend\Ether\EtherServer.fs:line 52
   --- End of inner exception stack trace ---
   at GWallet.Backend.Infrastructure.Report[a](Exception ex) in C:\Users\andres\Documents\Code\gwalletMASTER\src\GWallet.Backend\Infrastructure.fs:line 19
   at Program.main(String[] argv) in C:\Users\andres\Documents\Code\gwalletMASTER\src\GWallet.Frontend.Console\Program.fs:line 266

Unhandled Exception: System.TypeInitializationException: The type initializer for '<StartupCode$GWallet-Backend>.$EtherServer' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Nethereum.JsonRpc.Client.RpcClient..ctor(Uri baseUrl, AuthenticationHeaderValue authHeaderValue, JsonSerializerSettings jsonSerializerSettings)
   at Nethereum.Web3.Web3.IntialiseDefaultRpcClient(String url)
   at Nethereum.Web3.Web3..ctor(String url)
   at <StartupCode$GWallet-Backend>.$EtherServer..cctor() in C:\Users\andres\Documents\Code\gwalletMASTER\src\GWallet.Backend\Ether\EtherServer.fs:line 52
   --- End of inner exception stack trace ---
   at GWallet.Backend.Infrastructure.Report[a](Exception ex) in C:\Users\andres\Documents\Code\gwalletMASTER\src\GWallet.Backend\Infrastructure.fs:line 19
   at GWallet.Backend.Infrastructure.OnUnhandledException[a](Object sender, UnhandledExceptionEventArgs args) in C:\Users\andres\Documents\Code\gwalletMASTER\src\GWallet.Backend\Infrastructure.fs:line 25
   at GWallet.Backend.Infrastructure.SetupSentryHook@28-4.Invoke(Object delegateArg0, UnhandledExceptionEventArgs delegateArg1) in C:\Users\andres\Documents\Code\gwalletMASTER\src\GWallet.Backend\Infrastructure.fs:line 28