Try to fix build
Build errors start with:

/usr/lib/mono/4.5/Microsoft.FSharp.Targets (CoreCompile target) ->
2981 	/builds/knocte/geewallet/src/GWallet.Backend/FSharpUtil.fs(3,12): error FS1108: The type 'IEquatable`1' is required here and is unavailable. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
2982 	/builds/knocte/geewallet/src/GWallet.Backend/FSharpUtil.fs(13,17): error FS0039: The type 'Exception' is not defined
2983 	/builds/knocte/geewallet/src/GWallet.Backend/FSharpUtil.fs(13,17): error FS0039: The type 'Exception' is not defined
2984 	/builds/knocte/geewallet/src/GWallet.Backend/FSharpUtil.fs(13,17): error FS0039: The type 'Exception' is not defined
2985 	/builds/knocte/geewallet/src/GWallet.Backend/FSharpUtil.fs(52,64): error FS0001: The type 'ResultWrapper<'T>' is not compatible with the type 'exn'
2986 	/builds/knocte/geewallet/src/GWallet.Backend/FSharpUtil.fs(73,19): error FS0193: Type constraint mismatch. The type     ResultWrapper<'T>    is not compatible with type    exn    The type 'ResultWrapper<'T>' is not compatible with the type 'exn'
2987 	/builds/knocte/geewallet/src/GWallet.Backend/FSharpUtil.fs(111,32): error FS0039: The type 'TimeSpan' is not defined
2988 	/builds/knocte/geewallet/src/GWallet.Backend/FSharpUtil.fs(112,55): error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved.