scripts/snap_build.sh: clean before building
There's an issue with snap package generation after last merge,
but CI was failing with the wrong error message:

```
System.ArgumentException: Target directory already exists: /home/runner/work/geewallet/geewallet/staging/lib/geewallet
Parameter name: targetDir
  at FSI_0005.Fsdk.Misc.CopyDirectoryRecursively (System.IO.DirectoryInfo sourceDir, System.IO.DirectoryInfo targetDir,
```

This is because the snap package job is retried several times
(as per [1]), so we should clean up first before trying to
build, so that retries work.

[1] 30a7678fb4eb8e1c2582457c1a5b3865681a5b87