Frontend.XF(SendPage): include fiat value of fee when estimating it
However, I'm including a big TODO here because obviously this
will fail with no internet connection (and we need this for cold
storage mode).

For example:

System.AggregateException: One or more errors occurred. ---> System.Exception: Call to access the balance somehow returned unexpected error ---> System.AggregateException: One or more errors occurred. ---> System.Exception: Some problem when connecting to https://api.myetherapi.com/eth ---> GWallet.Backend.Ether.Server+UnhandledWebException: GWallet not prepared for this WebException with Status[2] ---> System.Net.WebException: Error: ConnectFailure (Network is unreachable) ---> System.Net.Sockets.SocketException: Network is unreachable
  at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b0] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.9.1.24/src/Xamarin.iOS/mcs/class/System/System.Net.Sockets/Socket.cs:879
  at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x00191] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.9.1.24/src/Xamarin.iOS/mcs/class/System/System.Net/WebConnection.cs:187
  --- End of inner exception stack trace ---
  at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.9.1.24/src/Xamarin.iOS/mcs/class/System/System.Net/HttpWebRequest.cs:902
  at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.9.1.24/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/threading/Tasks/FutureFactory.cs:550
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.9.1.24/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:152
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.9.1.24/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.9.1.24/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.9.1.24/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.9.1.24/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:535
  at System.Net.Http.HttpClientHandler+<SendAsync>d__64.MoveNext () [0x0029d] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.9.1.24/src/Xamarin.iOS/mcs/class/System.Net.Http/System.Net.Http/HttpClientHandler.cs:392
  --- End of inner exception stack trace ---
  at GWallet.Backend.Ether.Server.WaitOnTask[T,R] (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] func, T arg) [0x001c8] in /Users/andres/Documents/Code/gwalletFRONTEND/src/GWallet.Backend/Ether/EtherServer.fs:121
  at GWallet.Backend.Ether.Server+web3Func@232-8.Invoke (Nethereum.Web3.Web3 web3, System.String publicddress) [0x00000] in /Users/andres/Documents/Code/gwalletFRONTEND/src/GWallet.Backend/Ether/EtherServer.fs:232
  at Microsoft.FSharp.Core.OptimizedClosures+Invoke@3252[T2,TResult,T1].Invoke (T2 u) [0x00000] in /Users/builder/data/lanes/5909/f62de472/source/xamarin-macios/external/fsharp/src/fsharp/FSharp.Core/prim-types.fs:3252
  at GWallet.Backend.Ether.Server+GetConfirmedTokenBalance@235-2.Invoke (System.String arg10) [0x00000] in /Users/andres/Documents/Code/gwalletFRONTEND/src/GWallet.Backend/Ether/EtherServer.fs:235
  at Microsoft.FSharp.Core.FSharpFunc`2[T,TResult].InvokeFast[V] (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] func, T arg1, TResult arg2) [0x0001f] in <5abd71b7dff9fae1a7450383b771bd5a>:0
  at GWallet.Backend.Ether.Server+serverFuncs@138[T,R].Invoke (GWallet.Backend.Ether.Server+SomeWeb3 web3, T arg) [0x00000] in /Users/andres/Documents/Code/gwalletFRONTEND/src/GWallet.Backend/Ether/EtherServer.fs:141
  --- End of inner exception stack trace ---
  at <StartupCode$GWallet-Backend-NetStandard>.$FaultTolerantParallelClient+clo@108-12[E,T,R].Invoke (System.Exception _arg2) [0x000c8] in /Users/andres/Documents/Code/gwalletFRONTEND/src/GWallet.Backend/FaultTolerantParallelClient.fs:114
  at Microsoft.FSharp.Control.AsyncBuilderImpl+tryWithExnA@893[a].Invoke (System.Runtime.ExceptionServices.ExceptionDispatchInfo edi) [0x00000] in /Users/builder/data/lanes/5909/f62de472/source/xamarin-macios/external/fsharp/src/fsharp/FSharp.Core/control.fs:893
  at Microsoft.FSharp.Control.AsyncBuilderImpl+callA@851[b,a].Invoke (Microsoft.FSharp.Control.AsyncParams`1[T] args) [0x0002b] in /Users/builder/data/lanes/5909/f62de472/source/xamarin-macios/external/fsharp/src/fsharp/FSharp.Core/control.fs:855
  --- End of inner exception stack trace ---
  at System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) [0x00011] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.9.1.24/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:2157
  at System.Threading.Tasks.Task`1[TResult].GetResultCore (System.Boolean waitCompletionNotification) [0x0002b] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.9.1.24/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/threading/Tasks/Future.cs:562
  at System.Threading.Tasks.Task`1[TResult].get_Result () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.9.1.24/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/threading/Tasks/Future.cs:532
  at <StartupCode$GWallet-Backend-NetStandard>.$FaultTolerantParallelClient+clo@62-8[E,T,R].Invoke (System.Threading.Tasks.Task`1[TResult] _arg1) [0x00002] in /Users/andres/Documents/Code/gwalletFRONTEND/src/GWallet.Backend/FaultTolerantParallelClient.fs:62
  at Microsoft.FSharp.Control.AsyncBuilderImpl+args@835-1[a,b].Invoke (a a) [0x00000] in /Users/builder/data/lanes/5909/f62de472/source/xamarin-macios/external/fsharp/src/fsharp/FSharp.Core/control.fs:835
  --- End of inner exception stack trace ---
  at GWallet.Backend.Account+GetBalanceFromServerOrCache@34-4.Invoke (System.Exception _arg2) [0x00022] in /Users/andres/Documents/Code/gwalletFRONTEND/src/GWallet.Backend/Account.fs:43
  at Microsoft.FSharp.Control.AsyncBuilderImpl+tryWithExnA@893[a].Invoke (System.Runtime.ExceptionServices.ExceptionDispatchInfo edi) [0x00000] in /Users/builder/data/lanes/5909/f62de472/source/xamarin-macios/external/fsharp/src/fsharp/FSharp.Core/control.fs:893
  at Microsoft.FSharp.Control.AsyncBuilderImpl+callA@851[b,a].Invoke (Microsoft.FSharp.Control.AsyncParams`1[T] args) [0x0002b] in /Users/builder/data/lanes/5909/f62de472/source/xamarin-macios/external/fsharp/src/fsharp/FSharp.Core/control.fs:855
  --- End of inner exception stack trace ---
  at <StartupCode$GWallet-Frontend-XF>.$FrontendHelpers+DoubleCheckCompletion@61-1[T].Invoke () [0x00002] in /Users/andres/Documents/Code/gwalletFRONTEND/src/GWallet.Frontend.XF/FrontendHelpers.fs:62
  at Foundation.NSAsyncActionDispatcher.Apply () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.9.1.24/src/Xamarin.iOS/Foundation/NSAction.cs:163
  at at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.9.1.24/src/Xamarin.iOS/UIKit/UIApplication.cs:79
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x00038] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.9.1.24/src/Xamarin.iOS/UIKit/UIApplication.cs:63
  at GWalletFrontendXamForms.iOS.Main.main (System.String[] args) [0x00000] in /Users/andres/Documents/Code/gwalletFRONTEND/src/GWallet.Frontend.XamForms.iOS/AppDelegate.fs:24