Frontend.XF.Android: retarget from XamarinAndroid 9.0 to 10.0
The reason to do this is because after the upgrade of XF to 5.0 (previous
commit) we started getting this compilation error:

```
/Users/knocte/Documents/Code/geewalletFRONTEND/packages/Xamarin.Forms.5.0.0.2012/build/Xamarin.Forms.targets(5,5):
Error XF005: The $(TargetFrameworkVersion) for GWallet.Frontend.XF.Android (v9.0) is less than the minimum required $(TargetFrameworkVersion) for Xamarin.Forms (10.0).
You need to increase the $(TargetFrameworkVersion) for GWallet.Frontend.XF.Android. (XF005) (GWallet.Frontend.XF.Android)
```

After I changed it from v9.0 to v10.0 in the .fsproj file, and re-loading
the solution, VS4Mac hinted me to "retarget" the project, which caused
a lot of changes in the packages.config and the same .fsproj file.
Unfortunately, it still didn't compile, this time throwing this error:

```
/Users/knocte/Documents/Code/geewalletFRONTEND/packages/Xamarin.AndroidX.Migration.1.0.8/build/monoandroid90/Xamarin.AndroidX.Migration.targets(9,9): Error: Could not find 2 Android X assemblies, make sure to install the following NuGet packages:
 - Xamarin.AndroidX.MediaRouter
 - Xamarin.AndroidX.Palette
You can also copy-and-paste the following snippet into your .csproj file:
    <PackageReference Include="Xamarin.AndroidX.MediaRouter" Version="1.2.0" />
    <PackageReference Include="Xamarin.AndroidX.Palette" Version="1.0.0.5" /> (GWallet.Frontend.XF.Android)
```

But we will fix that in the next commit.