Backend/Ether(Server): add FIXME about buggy consistency checking
I just got this exception when querying the gas price:

____result:1430000000
____result:1500000000
____result:1000000000

GWallet.Backend.ResultInconsistencyException: Results obtained were not enough to be considered consistent (received: 3, consistent: 1, required: 2)
  at <StartupCode$GWallet-Backend>.$FaultTolerantParallelClient+clo@178-25[R,E].Invoke (Microsoft.FSharp.Core.Unit unitVar) [0x0002d] in <5b2e3da35952d4f0a7450383a33d2e5b>:0
  at Microsoft.FSharp.Control.AsyncBuilderImpl+callA@839[b,a].Invoke (Microsoft.FSharp.Control.AsyncParams`1[T] args) [0x00052] in <59964427904cf4daa745038327449659>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <bb7b695b8c6246b3ac1646577aea7650>:0
  at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a] (Microsoft.FSharp.Control.AsyncBuilderImpl+AsyncImplResult`1[T] res) [0x0002d] in <59964427904cf4daa745038327449659>:0
  at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronouslyInCurrentThread[a] (System.Threading.CancellationToken token, Microsoft.FSharp.Control.FSharpAsync`1[T] computation) [0x00029] in <59964427904cf4daa745038327449659>:0
  at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a] (System.Threading.CancellationToken token, Microsoft.FSharp.Control.FSharpAsync`1[T] computation, Microsoft.FSharp.Core.FSharpOption`1[T] timeout) [0x00014] in <59964427904cf4daa745038327449659>:0
  at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T] (Microsoft.FSharp.Control.FSharpAsync`1[T] computation, Microsoft.FSharp.Core.FSharpOption`1[T] timeout, Microsoft.FSharp.Core.FSharpOption`1[T] cancellationToken) [0x00071] in <59964427904cf4daa745038327449659>:0
  at GWallet.Frontend.Console.UserInteraction.AskFee (GWallet.Backend.IAccount account, GWallet.Backend.TransferAmount amount, System.String destination) [0x0008a] in <5b2e40c848ab50f3a7450383c8402e5b>:0
  at Program.SendPayment () [0x00032] in <5b2e40c848ab50f3a7450383c8402e5b>:0
  at Program.PerformOptions (System.Int32 numAccounts) [0x00094] in <5b2e40c848ab50f3a7450383c8402e5b>:0
  at Program.ProgramMainLoop[a] () [0x00023] in <5b2e40c848ab50f3a7450383c8402e5b>:0
  at Program.main (System.String[] argv) [0x00007] in <5b2e40c848ab50f3a7450383c8402e5b>:0
GWallet.Backend.ResultInconsistencyException: Results obtained were not enough to be considered consistent (received: 3, consistent: 1, required: 2)
  at <StartupCode$GWallet-Backend>.$FaultTolerantParallelClient+clo@178-25[R,E].Invoke (Microsoft.FSharp.Core.Unit unitVar) [0x0002d] in <5b2e3da35952d4f0a7450383a33d2e5b>:0
  at Microsoft.FSharp.Control.AsyncBuilderImpl+callA@839[b,a].Invoke (Microsoft.FSharp.Control.AsyncParams`1[T] args) [0x00052] in <59964427904cf4daa745038327449659>:0
--- End of stack trace from previous location where exception was thrown ---
  at GWallet.Backend.Infrastructure.Report[a] (System.Exception ex) [0x0000b] in <5b2e3da35952d4f0a7450383a33d2e5b>:0
  at Program.main (System.String[] argv) [0x00017] in <5b2e40c848ab50f3a7450383c8402e5b>:0
exception inside UnhandledException handler: Results obtained were not enough to be considered consistent (received: 3, consistent: 1, required: 2)

[ERROR] FATAL UNHANDLED EXCEPTION: GWallet.Backend.ResultInconsistencyException: Results obtained were not enough to be considered consistent (received: 3, consistent: 1, required: 2)
  at <StartupCode$GWallet-Backend>.$FaultTolerantParallelClient+clo@178-25[R,E].Invoke (Microsoft.FSharp.Core.Unit unitVar) [0x0002d] in <5b2e3da35952d4f0a7450383a33d2e5b>:0
  at Microsoft.FSharp.Control.AsyncBuilderImpl+callA@839[b,a].Invoke (Microsoft.FSharp.Control.AsyncParams`1[T] args) [0x00052] in <59964427904cf4daa745038327449659>:0
--- End of stack trace from previous location where exception was thrown ---
  at GWallet.Backend.Infrastructure.Report[a] (System.Exception ex) [0x0000b] in <5b2e3da35952d4f0a7450383a33d2e5b>:0
  at GWallet.Backend.Infrastructure.OnUnhandledException[a] (System.Object sender, System.UnhandledExceptionEventArgs args) [0x00006] in <5b2e3da35952d4f0a7450383a33d2e5b>:0
  at GWallet.Backend.Infrastructure+SetupSentryHook@28-4.Invoke (System.Object delegateArg0, System.UnhandledExceptionEventArgs delegateArg1) [0x00000] in <5b2e3da35952d4f0a7450383a33d2e5b>: