Backend/Ether: further squash yet another ETC inconsistency bug
As a follow-up to this recent commit [1], we had forgotten 2 extra places
where essentially "2 servers" was a hardcoded requirement, so we received
this in the frontend branch in a wallet installed from scratch:

Exception in Gtk# callback delegate
  Note: Applications can use GLib.ExceptionManager.UnhandledException to handle the exception.
GWallet.Backend.ResultInconsistencyException: Results obtained were not enough to be considered consistent (received: 1, consistent: 1, required: 2)
  at <StartupCode$GWallet-Backend-NetStandard>.$FaultTolerantParallelClient+clo@556-53[K,R,E].Invoke (GWallet.Backend.FinalResult`3[K,T,R] _arg3) [0x00202] in <5ebcf339be1c2694a745038339f3bc5e>:0
  at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b] (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt, Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] userCode, b result1) [0x00005] in <039b17603f7a807e0eeaa652dc64c784>:0
  at <StartupCode$GWallet-Backend-NetStandard>.$FaultTolerantParallelClient+clo@506-39[K,R,T].Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5ebcf339be1c2694a745038339f3bc5e>:0
  at <StartupCode$GWallet-Backend-NetStandard>.$FaultTolerantParallelClient+clo@302-24[K,R,T].Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5ebcf339be1c2694a745038339f3bc5e>:0
  at <StartupCode$GWallet-Backend-NetStandard>.$FaultTolerantParallelClient+WhenAny@118-7[K,R].Invoke (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt) [0x00000] in <5ebcf339be1c2694a745038339f3bc5e>:0
  at Microsoft.FSharp.Control.Trampoline.Execute (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] firstAction) [0x00020] in <039b17603f7a807e0eeaa652dc64c784>:0
--- End of stack trace from previous location where exception was thrown ---

  at GWallet.Frontend.XF.FrontendHelpers+MaybeCrash@251.Invoke () [0x0000b] in <5ebcf340303fdc7ea745038340f3bc5e>:0
  at Xamarin.Forms.Platform.GTK.GtkPlatformServices+<>c__DisplayClass5_0.<BeginInvokeOnMainThread>b__0 () [0x00000] in <edef467bfa4e49759076cb08940f626c>:0
  at GLib.Idle+IdleProxy.Invoke (System.IntPtr data) [0x00000] in <ed39f21b9e9343dcbd442a17ad356a9f>:0
  at GLib.SourceProxy.HandlerInternal (System.IntPtr data) [0x00000] in <ed39f21b9e9343dcbd442a17ad356a9f>:0
  at GLib.ExceptionManager.RaiseUnhandledException (System.Exception e, System.Boolean is_terminal) [0x00000] in <ed39f21b9e9343dcbd442a17ad356a9f>:0
  at GLib.SourceProxy.HandlerInternal (System.IntPtr data) [0x00000] in <ed39f21b9e9343dcbd442a17ad356a9f>:0
  at Gtk.Application.gtk_main () [0x00000] in <7aab76e87bce48a4b45cf7fa613cb70c>:0
  at Gtk.Application.Run () [0x00000] in <7aab76e87bce48a4b45cf7fa613cb70c>:0
  at GWallet.Frontend.XF.Gtk.Main.main (System.String[] argv) [0x00000] in <5ebcf345944123fea745038345f3bc5e>:0

[1] acfa8d7c588537864c8c699a49211f26890ae7bb