Frontend.XF.*: upgrade to FSharp.Core 4.5.2
Strangely enough (maybe after upgrading my VS4Mac), the
project Backend.NetStandard now appears to be built against
this new version of FSharp.Core (which I didn't upgrade
myself, and whose version is not in the .fsproj file).

If I don't sync the rest of the projects with this, they
would crash with:

System.TypeLoadException: Could not resolve type with token 0100000e (from typeref, class/assembly Microsoft.FSharp.Control.AsyncActivation`1, FSharp.Core, Version=4.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
  at GWallet.Frontend.XF.FrontendHelpers+DoubleCheckCompletionAsync@166-4.Invoke () [0x00002] in /Users/andres/Documents/Code/gwalletFRONTENDPRISTINE/src/GWallet.Frontend.XF/FrontendHelpers.fs:167
  at Foundation.NSAsyncActionDispatcher.Apply () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/Foundation/NSAction.cs:152
  at at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/UIKit/UIApplication.cs:79
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0002c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/UIKit/UIApplication.cs:63
  at GWallet.Frontend.XF.iOS.Main.main (System.String[] args) [0x00000] in /Users/andres/Documents/Code/gwalletFRONTENDPRISTINE/src/GWallet.Frontend.XF.iOS/AppDelegate.fs:24