Frontend.XF: fix crash caused by threading issue (UI thread)
Widgets were being updated within a non-main thread and led to this
crash when debugging Android in the emulator for me:

Android.Util.AndroidRuntimeException: Only the original thread that created a view hierarchy can touch its views.
  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0008e] in <dac4c5a4b77f4e61a5e6d9d3050dfb9f>:0
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0001f] in <dac4c5a4b77f4e61a5e6d9d3050dfb9f>:0
  at Android.Widget.TextView.set_TextFormatted (Java.Lang.ICharSequence value) [0x00029] in <55654ebe9f2a48e6bade2862bb243f94>:0
  at Android.Widget.TextView.set_Text (System.String value) [0x0000d] in <55654ebe9f2a48e6bade2862bb243f94>:0
  at Xamarin.Forms.Platform.Android.FastRenderers.LabelRenderer.UpdateText () [0x000f1] in d:\a\1\s\Xamarin.Forms.Platform.Android\FastRenderers\LabelRenderer.cs:410
  at Xamarin.Forms.Platform.Android.FastRenderers.LabelRenderer.OnElementPropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e) [0x00123] in d:\a\1\s\Xamarin.Forms.Platform.Android\FastRenderers\LabelRenderer.cs:291
  at at (wrapper delegate-invoke) <Module>.invoke_void_object_PropertyChangedEventArgs(object,System.ComponentModel.PropertyChangedEventArgs)
  at Xamarin.Forms.BindableObject.OnPropertyChanged (System.String propertyName) [0x00000] in d:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:229
  at Xamarin.Forms.Element.OnPropertyChanged (System.String propertyName) [0x00000] in d:\a\1\s\Xamarin.Forms.Core\Element.cs:353
  at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent) [0x00114] in d:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:461
  at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes) [0x00173] in d:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:397
  at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value, System.Boolean fromStyle, System.Boolean checkAccess) [0x00042] in d:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:334
  at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value) [0x00000] in d:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:311
  at Xamarin.Forms.Label.set_Text (System.String value) [0x00000] in d:\a\1\s\Xamarin.Forms.Core\Label.cs:139
  at <StartupCode$GWallet-Frontend-XF>.$SendPage.xaml+UpdateEquivalentFiatLabel@469-5.Invoke (GWallet.Backend.MaybeCached`1[T] _arg11) [0x002bc] in /Users/knocte/Documents/Code/geewalletFRONTEND/src/GWallet.Frontend.XF/SendPage.xaml.fs:507
  at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b] (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt, Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] userCode, b result1) [0x00005] in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:416
  at Microsoft.FSharp.Control.Trampoline.Execute (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] firstAction) [0x00020] in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:109
  at Microsoft.FSharp.Control.AsyncPrimitives+Start@907-1.Invoke (System.Runtime.ExceptionServices.ExceptionDispatchInfo edi) [0x00000] in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:0
  at Microsoft.FSharp.Control.Trampoline.Execute (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] firstAction) [0x0009c] in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:120
  at Microsoft.FSharp.Control.TrampolineHolder.ExecuteWithTrampoline (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] firstAction) [0x00031] in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:177
  at Microsoft.FSharp.Control.AsyncPrimitives.continuation@942[T] (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt, System.Boolean useCcontForTaskCancellation, System.Threading.Tasks.Task`1[TResult] completedTask) [0x00000] in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:943
  at Microsoft.FSharp.Control.AsyncPrimitives+taskContinueWith@956[T].Invoke (System.Threading.Tasks.Task`1[TResult] delegateArg0) [0x00000] in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:956
  at System.Threading.Tasks.ContinuationTaskFromResultTask`1[TAntecedentResult].InnerInvoke () [0x00024] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/TaskContinuation.cs:155
  at System.Threading.Tasks.Task.Execute () [0x00000] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2319
  at android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
  at at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:7313)
  at at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1161)
  at at android.view.View.requestLayout(View.java:21995)
  at at android.view.View.requestLayout(View.java:21995)
  at at android.view.View.requestLayout(View.java:21995)
  at at android.view.View.requestLayout(View.java:21995)
  at at android.view.View.requestLayout(View.java:21995)
  at at android.view.View.requestLayout(View.java:21995)
  at at android.widget.RelativeLayout.requestLayout(RelativeLayout.java:360)
  at at android.view.View.requestLayout(View.java:21995)
  at at android.view.View.requestLayout(View.java:21995)
  at at android.view.View.requestLayout(View.java:21995)
  at at android.view.View.requestLayout(View.java:21995)
  at at android.view.View.requestLayout(View.java:21995)
  at at android.view.View.requestLayout(View.java:21995)
  at at android.view.View.requestLayout(View.java:21995)
  at at android.view.View.requestLayout(View.java:21995)
  at at android.view.View.requestLayout(View.java:21995)
  at at android.view.View.requestLayout(View.java:21995)
  at at android.view.View.requestLayout(View.java:21995)
  at at android.widget.TextView.checkForRelayout(TextView.java:8531)
  at at android.widget.TextView.setText(TextView.java:5394)
  at at android.widget.TextView.setText(TextView.java:5250)
  at at android.widget.TextView.setText(TextView.java:5207)