Frontend.XF.UWP: upgrade toolkit, to avoid mysterious errors
When trying the option "(right click on project->)Publish->Create App
Packages..." I was getting the error:

ILT0005: 'C:\Users\knoct\.nuget\packages\microsoft.net.native.compiler\2.0.2\tools\x64\ilc\ilc.exe --gatekeeper @"C:\Users\knoct\Source\Repos\geewalletFRONTEND\src\GWallet.Frontend.XF.UWP\obj\x64\Release\ilc\intermediate\gkargs.rsp"' returned exit code 1	GWallet.Frontend.XF.UWP

Which seemed to be a limiation of UWP wrt F#, but after bringing it up
in github[1] I was recommended to follow the recommendation of hacking
my local environment[2]. I did this in the recommended path:

C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\runtime.win10-x64.microsoft.net.native.compiler\2.2.7-rel-27913-00\tools\x64\ilc\tools\GatekeeperConfig.xml

But it didn't have any effect. So I did it in this path instead, which
seems more appropriate by reading the initial compilation error I had:

C:\Users\<MyUserName>\.nuget\packages\microsoft.net.native.compiler\2.0.2\tools\x64\ilc\tools\GatekeeperConfig.xml

But the result of doing this was this strange error:

Internal compiler error: Object reference not set to an instance of an object.

So I decided to upgrade the nuget packages of the project related to the
UWP SDK (from 6.0.4 to 6.2.9 as this diff shows), and it seems to have
helped here because I don't get this error anymore (but others which I'll
fix in subsequent commits).

[1] https://github.com/dotnet/corert/issues/6055#issuecomment-579694246
[2] https://github.com/dotnet/corert/issues/5780#issuecomment-396951719