Backend/JsonRpcSharp: catch weird NotSupportedException to retry
This one is weird, but it keeps happening often, so I'm
catching it so that FaultTolerantClient can ignore it and
retry.

The whole beast is:

System.AggregateException: One or more errors occurred. ---> System.NotSupportedException: This protocol version is not supported.
  at System.Net.Sockets.Socket.BeginConnect (System.Net.IPAddress address, System.Int32 port, System.AsyncCallback requestCallback, System.Object state) [0x00050] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/src/Xamarin.iOS/mcs/class/referencesource/System/net/System/Net/Sockets/Socket.cs:3157
  at System.Net.Sockets.TcpClient.BeginConnect (System.Net.IPAddress address, System.Int32 port, System.AsyncCallback requestCallback, System.Object state) [0x00006] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/src/Xamarin.iOS/mcs/class/referencesource/System/net/System/Net/Sockets/TCPClient.cs:375
  at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncImpl[TArg1,TArg2] (System.Func`5[T1,T2,T3,T4,TResult] beginMethod, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, TArg1 arg1, TArg2 arg2, System.Object state, System.Threading.Tasks.TaskCreationOptions creationOptions) [0x00170] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/threading/Tasks/FutureFactory.cs:1162
  at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2] (System.Func`5[T1,T2,T3,T4,TResult] beginMethod, System.Action`1[T] endMethod, TArg1 arg1, TArg2 arg2, System.Object state, System.Threading.Tasks.TaskCreationOptions creationOptions) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/threading/Tasks/TaskFactory.cs:1129
  at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2] (System.Func`5[T1,T2,T3,T4,TResult] beginMethod, System.Action`1[T] endMethod, TArg1 arg1, TArg2 arg2, System.Object state) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/threading/Tasks/TaskFactory.cs:1090
  at System.Net.Sockets.TcpClient.ConnectAsync (System.Net.IPAddress address, System.Int32 port) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/src/Xamarin.iOS/mcs/class/referencesource/System/net/System/Net/Sockets/TCPClient.cs:403
  at GWallet.Backend.JsonRpcSharp+Client.Connect () [0x00149] in /Users/andres/Documents/Code/gwalletFRONTEND/src/GWallet.Backend/JsonRpcSharp.fs:128
  at GWallet.Backend.JsonRpcSharp+Client.Request (System.String request) [0x00011] in /Users/andres/Documents/Code/gwalletFRONTEND/src/GWallet.Backend/JsonRpcSharp.fs:139
  at GWallet.Backend.UtxoCoin.StratumClient.Request[R] (System.String jsonRequest) [0x0006a] in /Users/andres/Documents/Code/gwalletFRONTEND/src/GWallet.Backend/UtxoCoin/StratumClient.fs:123
  at GWallet.Backend.UtxoCoin.StratumClient.ServerVersion (System.Version clientVersion, System.Version protocolVersion) [0x00035] in /Users/andres/Documents/Code/gwalletFRONTEND/src/GWallet.Backend/UtxoCoin/StratumClient.fs:172
  at GWallet.Backend.UtxoCoin.ElectrumClient.Init () [0x0005b] in /Users/andres/Documents/Code/gwalletFRONTEND/src/GWallet.Backend/UtxoCoin/ElectrumClient.fs:27
  at GWallet.Backend.UtxoCoin.ElectrumClient..ctor (GWallet.Backend.UtxoCoin.ElectrumServer electrumServer) [0x0000f] in /Users/andres/Documents/Code/gwalletFRONTEND/src/GWallet.Backend/UtxoCoin/ElectrumClient.fs:33
  at GWallet.Backend.UtxoCoin.Account+randomizedFuncs@65[T,R].Invoke (GWallet.Backend.UtxoCoin.ElectrumServer es, T arg) [0x00115] in /Users/andres/Documents/Code/gwalletFRONTEND/src/GWallet.Backend/UtxoCoin/UtxoCoinAccount.fs:78
  at Microsoft.FSharp.Core.OptimizedClosures+Invoke@3252[T2,TResult,T1].Invoke (T2 u) [0x00000] in /Users/builder/data/lanes/5808/1c6f300e/source/xamarin-macios/external/fsharp/src/fsharp/FSharp.Core/prim-types.fs:3252
  at <StartupCode$GWallet-Backend-NetStandard>.$FaultTolerantClient+queryInternal@39D[T,R,E].Invoke (System.UInt16 retries) [0x0019e] in /Users/andres/Documents/Code/gwalletFRONTEND/src/GWallet.Backend/FaultTolerantClient.fs:65
  at <StartupCode$GWallet-Backend-NetStandard>.$FaultTolerantClient+queryInternal@78-6[R].Invoke (System.UInt16 arg50) [0x00000] in /Users/andres/Documents/Code/gwalletFRONTEND/src/GWallet.Backend/FaultTolerantClient.fs:78
  at <StartupCode$GWallet-Backend-NetStandard>.$FaultTolerantClient+queryInternal@39D[T,R,E].Invoke (System.UInt16 retries) [0x00247] in /Users/andres/Documents/Code/gwalletFRONTEND/src/GWallet.Backend/FaultTolerantClient.fs:78
  at GWallet.Backend.FaultTolerantClient`1[E].Query[T,R] (T args, Microsoft.FSharp.Collections.FSharpList`1[T] funcs) [0x00047] in /Users/andres/Documents/Code/gwalletFRONTEND/src/GWallet.Backend/FaultTolerantClient.fs:86
  at GWallet.Backend.UtxoCoin.Account.GetBalance (GWallet.Backend.IAccount account) [0x00006] in /Users/andres/Documents/Code/gwalletFRONTEND/src/GWallet.Backend/UtxoCoin/UtxoCoinAccount.fs:88
  at GWallet.Backend.UtxoCoin.Account.GetConfirmedBalance (GWallet.Backend.IAccount account) [0x00000] in /Users/andres/Documents/Code/gwalletFRONTEND/src/GWallet.Backend/UtxoCoin/UtxoCoinAccount.fs:95
  at GWallet.Backend.Account.GetBalanceFromServerOrCache (GWallet.Backend.IAccount account, System.Boolean onlyConfirmed) [0x000ae] in /Users/andres/Documents/Code/gwalletFRONTEND/src/GWallet.Backend/Account.fs:30
  at GWallet.Backend.Account.GetConfirmedBalance (GWallet.Backend.IAccount account) [0x00000] in /Users/andres/Documents/Code/gwalletFRONTEND/src/GWallet.Backend/Account.fs:43
  at GWallet.Backend.Account.GetShowableBalance (GWallet.Backend.IAccount account) [0x00007] in /Users/andres/Documents/Code/gwalletFRONTEND/src/GWallet.Backend/Account.fs:47
  at System.Threading.Tasks.Task`1[TResult].InnerInvoke () [0x0000f] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/threading/Tasks/Future.cs:680
  at System.Threading.Tasks.Task.Execute () [0x00010] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:2502
  --- End of inner exception stack trace ---
  at System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) [0x00011] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:2157
  at System.Threading.Tasks.Task`1[TResult].GetResultCore (System.Boolean waitCompletionNotification) [0x0002b] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/threading/Tasks/Future.cs:562
  at System.Threading.Tasks.Task`1[TResult].get_Result () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/threading/Tasks/Future.cs:532
  at GWallet.Frontend.XF.BalancesPage.PopulateGrid (System.Collections.Generic.IEnumerable`1[T] initialBalancesTasksWithDetails) [0x00153] in /Users/andres/Documents/Code/gwalletFRONTEND/src/GWallet.Frontend.XF/BalancesPage.xaml.fs:75
  at <StartupCode$GWallet-Frontend-XF>.$BalancesPage.xaml+Init@147-6.Invoke () [0x00002] in /Users/andres/Documents/Code/gwalletFRONTEND/src/GWallet.Frontend.XF/BalancesPage.xaml.fs:148
  at Foundation.NSAsyncActionDispatcher.Apply () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/src/Xamarin.iOS/Foundation/NSAction.cs:163
  at at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/src/Xamarin.iOS/UIKit/UIApplication.cs:79
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x00038] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/src/Xamarin.iOS/UIKit/UIApplication.cs:63
  at GWalletFrontendXamForms.iOS.Main.main (System.String[] args) [0x00000] in /Users/andres/Documents/Code/gwalletFRONTEND/src/GWallet.Frontend.XamForms.iOS/AppDelegate.fs:24